### ISSUE TITLE
accounts ui: List of accounts doesn't scroll when more than a screenful

### ISSUE THREAD

**Issue by chrisbobbe** [zulip/zulip-flutter#100]

**Comment by sm-sayedi** [comment]
I would like to work on this issue!

My work so far:

<table>
    <tr>
        <td><b>Before</b></td>
        <td><b>After</b></td>
    </tr>
    <tr>
        <td><img src="https://github.com/zulip/zulip-flutter/assets/59946442/36ebfeb9-76b3-485f-a59e-1054bab8448a" width="300"/></td>
        <td><img src="https://github.com/zulip/zulip-flutter/assets/59946442/c8ddbe32-96e1-477d-b4ed-58e0e903f912" width="300"/></td>
    </tr>
</table>

**Comment by gnprice** [comment]
Sure — please go ahead. That behavior looks good.
