### ISSUE TITLE
Previews when composing a message

### ISSUE THREAD

**Issue by gnprice** [zulip/zulip-flutter#1001]
This is a useful feature in web:
https://zulip.com/help/preview-your-message-before-sending
and it would be useful in mobile too.

(It's not *as* common to want it in mobile, I think, because one tends to stick to shorter messages with simpler formatting. But that's far from absolute.)

**Comment by gnprice** [comment]
We had a user request for this the other day:
https://chat.zulip.org/#narrow/channel/48-mobile/topic/iOS.20feedback.20for.20Julia.20community.20member/near/1961857
https://chat.zulip.org/#narrow/channel/48-mobile/topic/iOS.20feedback.20for.20Julia.20community.20member/near/1963803

They raised code blocks and LaTeX as particularly useful situations for a preview.

**Comment by whodivyanshu** [comment]
hey, 
I am working on this issue
![IMG_0899](https://github.com/user-attachments/assets/56c530d3-cfef-4d41-bec1-d1233f94bc6f)

Please correct me If i am doing something wrong 
So, I checked the website of zulip and checked how this view button works
I started working on this issue and I have showed the message in the dialogbox so this is how it looks like .

**Comment by whodivyanshu** [comment]
So, the model this is right or should i do same like what is done in the web

**Comment by gnprice** [comment]
Let's put the preview in the compose box, replacing the content input, just like in Zulip web.

And the text styling should be sure to be the same as it is in the message list — after all, the point of the preview is to see how your message will look if you send it. In the screenshot above, it looks like the text is smaller.

**Comment by whodivyanshu** [comment]
https://github.com/user-attachments/assets/27fa956f-2f7d-4c4d-8409-4b124a025351

i have done this to the text can you please check is it correct

**Comment by chrisbobbe** [comment]
Please post a screenshot where the message uses some Zulip Markdown features, like:

```
*italic*
```

```
**bold**
```

````
```
code block
```
````

````
```spoiler 
testing
```
````

```
[image2.jpg](/user_uploads/2/5b/4T9c_99X3W2IYB62fKnIzyvk/image2.jpg) 
```

This feature will be complex to implement. It will require some work toward #488, at least to address the fact that the image-preview widget currently depends on a `Message` object (for the lightbox), and we don't have a `Message` object in this context.

**Comment by whodivyanshu** [comment]
I have done the bold and the italic thing but right now i am working on the ``` and the image preview 

https://github.com/user-attachments/assets/592d207d-324f-4d56-9bc1-c7f2ed959f6d

**Comment by gnprice** [comment]
@whodivyanshu It doesn't sound like you're approaching this in a way that's going to work. A successful approach to this issue isn't going to involve re-implementing Zulip's message content features one by one.

If you want to share more details of what you're doing, please start a PR thread or a chat thread in `#mobile-dev-help`. Let's keep this issue thread clear so it's readable for discussion of the issue itself.

**Comment by gnprice** [comment]
Oh hey, it turns out we already had an issue for this:
* #178 

I'll close this thread in favor of that one, and consolidate to there the useful bits of information from this thread.
