### ISSUE TITLE
"Whole channel" button from topic narrows

### ISSUE THREAD

**Issue by gnprice** [zulip/zulip-flutter#1040]
When viewing the message list for a topic narrow, we should have a quick way to get to the enclosing stream/channel narrow.

In the legacy zulip-mobile app, this is just a button in the app bar, with an "up" icon. In a future with a fancier app bar for these message lists (as in #1039), we may do something fancier; but for now, let's just follow the legacy app and have a button.

One update from the legacy app, though: instead of an "up" icon, let's use the "all messages" / "combined feed" icon. That's the same one that web now uses in the channel menu in the left sidebar, for the new "Go to channel feed" option.

I'm giving this the near-term "Beta 4" milestone, because when I was demoing Zulip in person a lot earlier this week, I repeatedly found the lack of it awkward. (Specifically the use case was that I was viewing one conversation and wanted to start a new one. There are other ways we could serve that use case; but any deeper re-imagining of that UX is a post-launch issue.)

**Comment by Dhanesh-Sawant** [comment]
Hi @gnprice 

I've implemented the "Whole channel" button within the MessageListAppBarTitle for the TopicNarrow. Here's a brief overview of the approach I've taken:

In the TopicNarrow case of the MessageListAppBarTitle component, I'm currently returning a Row that includes:
The _buildStreamRow method to display the stream and topic names.

An IconButton (currently with an "up" arrow icon) to navigate to the enclosing channel view.
The IconButton triggers Navigator.pushReplacement to navigate to the MessageListPage with a ChannelNarrow for the given streamId. This way, it directly takes the user back to the channel view without adding a new route to the navigation stack.


class MessageListAppBarTitle extends StatelessWidget {
  const MessageListAppBarTitle({super.key, required this.narrow});

  final Narrow narrow;

  Widget _buildStreamRow(BuildContext context, {
    ZulipStream? stream,
    required String text,
  }) {
    // A null [Icon.icon] makes a blank space.
    final icon = (stream != null) ? iconDataForStream(stream) : null;
    return Row(
      mainAxisSize: MainAxisSize.min,
      // TODO(design): The vertical alignment of the stream privacy icon is a bit ad hoc.
      //   For screenshots of some experiments, see:
      //     https://github.com/zulip/zulip-flutter/pull/219#discussion_r1281024746
      crossAxisAlignment: CrossAxisAlignment.center,
      children: [
        Icon(size: 16, icon),
        const SizedBox(width: 4),
        Flexible(child: Text(text)),
      ]);
  }

  @override
  Widget build(BuildContext context) {
    final zulipLocalizations = ZulipLocalizations.of(context);

    switch (narrow) {
      case CombinedFeedNarrow():
        return Text(zulipLocalizations.combinedFeedPageTitle);

      case MentionsNarrow():
        return Text(zulipLocalizations.mentionsPageTitle);

      case StarredMessagesNarrow():
        return Text(zulipLocalizations.starredMessagesPageTitle);

      case ChannelNarrow(:var streamId):
        final store = PerAccountStoreWidget.of(context);
        final stream = store.streams[streamId];
        final streamName = stream?.name ?? '(unknown channel)';
        return _buildStreamRow(context, stream: stream, text: streamName);

      case TopicNarrow(:var streamId, :var topic):
        final store = PerAccountStoreWidget.of(context);
        final stream = store.streams[streamId];
        final streamName = stream?.name ?? '(unknown channel)';
        return Row(
          children: [
            Expanded(
              child: _buildStreamRow(
                context,
                stream: stream,
                text: "$streamName > $topic",
              ),
            ),
            IconButton(
              icon: Icon(Icons.arrow_upward),
              tooltip: 'Go to channel feed',
              onPressed: () => Navigator.pushReplacement(
                context,
                MessageListPage.buildRoute(
                  context: context,
                  narrow: ChannelNarrow(streamId),
                ),
              ),
            ),
          ],
        );

      case DmNarrow(:var otherRecipientIds):
        final store = PerAccountStoreWidget.of(context);
        if (otherRecipientIds.isEmpty) {
          return const Text("DMs with yourself");
        } else {
          final names = otherRecipientIds.map((id) => store.users[id]?.fullName ?? '(unknown user)');
          return Text("DMs with ${names.join(", ")}"); // TODO show avatars
        }
    }
  }
}

output:-

Uploading zulip-flutter – message_list.dart 2024-11-09 17-11-08.mp4…


Could you confirm if this approach aligns with the design intent for navigating to the enclosing stream/channel narrow?

**Comment by Dhanesh-Sawant** [comment]
@gnprice @chrisbobbe can u please go through the above approach?

**Comment by PIG208** [comment]
@Dhanesh-Sawant If you want to share more details of what you're doing, please start a PR thread or a chat thread in [#mobile-dev-help](https://chat.zulip.org/#narrow/channel/516-mobile-dev-help). Let's keep this issue thread clear so it's readable for discussion of the issue itself.
