### ISSUE TITLE
New channel wildcard mentions are rendered as "unimplemented"

### ISSUE THREAD

**Issue by sm-sayedi** [zulip/zulip-flutter#1064]
While working on #889, I realized that the channel wildcard mentions (`@all`, `@everyone`, `@channel`, `@stream`) are rendered as "unimplemented". This behavior is only for newer messages (after [#31075](https://github.com/zulip/zulip/pull/31075) is merged in [zulip](https://github.com/zulip/zulip)), the older messages with these wildcard mentions are rendered correctly. This is how the HTML text for older and newer messages looks like:

```html
// older messages
<span class="user-mention" data-user-id="*">@all</span>

// newer messages
<span class="user-mention channel-wildcard-mention" data-user-id="*">@all</span>
```

There seems to have been an additional class (`channel-wildcard-mention`) added. So, I think we have to support both the previous format and the current one.

**Comment by gnprice** [comment]
Hmm! Interesting, thanks for the report.

Can you link to an example message with this format? Or is it not currently possible to generate on chat.zulip.org for some reason?

Using the survey tool from #190, I don't see any examples of this in public messages on chat.zulip.org. See e.g. the output copied in the description of #921.

**Comment by sm-sayedi** [comment]
I couldn't find any such message on chat.zulip.org and because I don't have permission to use `@all` and similar mentions, I couldn't generate one too. I spotted this in my own organization which I use for test purposes.

> Using the survey tool from #190, I don't see any examples of this in public messages on chat.zulip.org.

I am not sure, but maybe that's because there are no new messages with such mentions.

Here are the screenshots (of my organization) both from the web and mobile:

### Web
![image](https://github.com/user-attachments/assets/16130670-60b2-4dc5-bb45-5504305c5045)

### Mobile
<img src="https://github.com/user-attachments/assets/fe81d1a0-fbbd-490e-8ad4-7ccf95c3dc64" width="300" />

**Comment by gnprice** [comment]
Aha, that'd do it. Yeah, we have this permission set: 
![image](https://github.com/user-attachments/assets/3e4ff3de-10ab-4fda-bc87-81e935993a78)

> Who can notify a large number of users with a wildcard mention [(i)](https://chat.zulip.org/help/restrict-wildcard-mentions)
> Admins and moderators

so in most channels, nobody can use @-all and the like except admins and moderators, and I guess in practice we never do.

@rajveermalviya would you put this issue on your queue? Looks like probably a small one.

For making an example message to point to in the test, you can send to an ad-hoc testing channel with few users — see the help page linked in the quote above.

It seems like this was an earlier case of the same [process failure](https://chat.zulip.org/#narrow/channel/378-api-design/topic/notation.20for.20near.20links/near/1976012) that caused #1046 to arise suddenly a couple of weeks ago. But this one was back in August, before that discussion.

**Comment by sm-sayedi** [comment]
@gnprice Can I work on this one? I also plan to work on #892 first and then return to #889 so that all the related mentions are parsed correctly!

**Comment by sm-sayedi** [comment]
By the way, here's the link to a CZO message with channel wildcard mentions:
https://chat.zulip.org/#narrow/channel/497-my-test/topic/channel.20wildcard.20mentions/near/1984716

**Comment by gnprice** [comment]
Sure! Please go ahead.
