### ISSUE TITLE
compose: Error banner for deactivated DM recipient has lost its top margin

### ISSUE THREAD

**Issue by chrisbobbe** [zulip/zulip-flutter#1089]
In 3adb39557c51604d85741664026c85225fba52fa (fyi @PIG208), we regressed on the layout of the error banner shown when a DM recipient is deactivated:

| Before | After |
| --- | --- |
| <img width="675" alt="image" src="https://github.com/user-attachments/assets/32de2f0e-109c-40bb-872e-6dfa273fb19f"> | <img width="675" alt="image" src="https://github.com/user-attachments/assets/3dc3047e-8e0d-4faa-b5aa-b31dbe272d2e"> |

The top margin disappeared, and it looks buggy.

I plan to fix this in a PR that's mostly focused on proposing some prep refactors to make a cleaner starting point for #720. (If those refactors seem good, Zixuan can rebase #924 past them.)

**Comment by PIG208** [comment]
Thanks to sending this issue! eb9fccd7515b50ec30148eb688b3d6c2b6bb3b31 (from #924) intersects with this by using the same `_ErrorBanner` class for the error banner here and the one that appears above the compose box.

I noticed that I didn't post a screenshot for this. Added it to #924. Also starting a discussion on the design of this.
