### ISSUE TITLE
Dart SDK change breaks background notifications

### ISSUE THREAD

**Issue by gnprice** [zulip/zulip-flutter#1119]
On upgrading to Flutter from current main, and running in release mode, the app no longer shows notifications on Android when it was in the background. This burst of error messages appears in logcat:

```
DartVM   E  ERROR: To access 'package:zulip/notifications/receive.dart::NotificationService' from native code, it must be annotated.
            ERROR: See https://github.com/dart-lang/sdk/blob/master/runtime/docs/compiler/aot/entry_point_pragma.md
flutter  E  [ERROR:flutter/lib/ui/dart_runtime_hooks.cc(38)] Dart Error: ERROR: To access 'package:zulip/notifications/receive.dart::NotificationService' from native code, it must be annotated.
            ERROR: See https://github.com/dart-lang/sdk/blob/master/runtime/docs/compiler/aot/entry_point_pragma.md
flutter  E  [ERROR:flutter/shell/common/shell.cc(115)] Dart Error: ERROR: To access 'package:zulip/notifications/receive.dart::NotificationService' from native code, it must be annotated.
            ERROR: See https://github.com/dart-lang/sdk/blob/master/runtime/docs/compiler/aot/entry_point_pragma.md
flutter  E  [ERROR:flutter/shell/common/shell.cc(115)] Dart Error: ERROR: To access 'package:zulip/notifications/receive.dart::NotificationService' from native code, it must be annotated.
                                                                                                    ERROR: See https://github.com/dart-lang/sdk/blob/master/runtime/docs/compiler/aot/entry_point_pragma.md
```

It looks like the relevant upstream commit is probably this one:
https://github.com/dart-lang/sdk/commit/9b06e26620a081c89931e5618336ff23dc6083be
which is also the latest commit to touch that linked docs page.

AFAICT those docs don't actually say that we should need to annotate the class. We already do annotate the static *method* that we ask native code to call:
```dart
  @pragma('vm:entry-point')
  static Future<void> _onBackgroundMessage(FirebaseRemoteMessage message) async {
```
Well, at least the error message is nice and clear, though. We'll annotate the class too.

**Comment by gnprice** [comment]
This makes a good example of why it'd be valuable for us to have end-to-end testing for notifications:
* #758

**Comment by miklcct** [comment]
I have got the same issue on state restoration and adding the pragma on the class fixed the issue for me.
