### ISSUE TITLE
"About Zulip" in main menu

### ISSUE THREAD

**Issue by gnprice** [zulip/zulip-flutter#1128]
The choose-account page has a menu with one item, "About Zulip", taking you to a page with that title. That page in turn has the version of the Zulip app, and an option to see the list of licenses for various open-source software used in the app.

Now that we have (after #1035 / #1076) a new overall navigation scheme, we should also add an "About Zulip" option in the main menu. That seems a more natural place for people to find it.

(It should also remain available in its existing location on the choose-account page. That ensures it's always possible to reach, even in a scenario where you can't get to the home page because the data can't be loaded from the server.)

Reported in [a chat thread](https://chat.zulip.org/#narrow/channel/48-mobile/topic/mobile.20beta.20feedback/near/1998560).

**Comment by Spyyy004** [comment]
Hey, I would love to work on this. Do you guys assign issues or i can start working straightaway?

**Comment by chrisbobbe** [comment]
Please take a look at the Zulip project's guide to getting involved with the code:

https://zulip.readthedocs.io/en/latest/contributing/contributing.html#your-first-codebase-contribution
https://zulip.readthedocs.io/en/latest/contributing/contributing.html#picking-an-issue-to-work-on

**Comment by Spyyy004** [comment]
Hey, By main menu do you mean this section?
<img width="242" alt="Screenshot 2024-12-12 at 17 27 22" src="https://github.com/user-attachments/assets/3e19c28f-64ce-40dc-8a45-3e1b5acdf902" />

**Comment by tomlin7** [comment]
Hey @gnprice I have worked on this feature and have added an **About Zulip** button to the main menu of the app, proceeding to open a PR on this.
