### ISSUE TITLE
Make combined feed quicker to reach

### ISSUE THREAD

**Issue by gnprice** [zulip/zulip-flutter#1164]
Currently in order to reach the combined feed, it takes two taps: the menu button in the bottom nav bar, and then the "Combined feed" option in the middle of the menu.

We've heard from a couple of users ([chat thread](https://chat.zulip.org/#narrow/channel/48-mobile/topic/combined.20feed/near/2003399)) that the combined feed is the most important view for them on mobile, and it'd be good to make it quicker to get to.

For example it could appear as one of the options in the bottom navigation bar on the home page. OTOH one tricky thing there would be that we currently don't show the bottom nav bar on message lists (rationale [here](https://chat.zulip.org/#narrow/channel/243-mobile-team/topic/UI.20redesign.3A.20root.20level.20nav/near/1908220) and in the message from Vlad just below that); so we'd have the oddity of tapping a bottom nav bar button give you a page where the bottom nav bar is gone, or else we'd show a bottom nav bar there after all despite the reasons we currently don't do that.

This issue thread is here to help us track user feedback for future design conversations. This is not an issue that's ready for someone to pick up and work on.

**Comment by chrisbobbe** [comment]
Another user saying that "Combined feed" is the most important view for them:

https://chat.zulip.org/#narrow/channel/48-mobile/topic/Flutter.20app/near/2008115
> - Keeping the bottom bar of buttons but not the top makes usage very clunky in my organisations: The most important views to me are, in the following order: Combined feed, Channels, (Profile), Inbox, DMs, Search, Starred messages, Mentions. So losing the top bar and only having Inbox, Channels, DMs, and Menu makes navigation very cumbersome.

**Comment by chrisbobbe** [comment]
Related:
- #517

**Comment by chrisbobbe** [comment]
Another user saying "Combined feed" is important to them, in a beta-feedback email to support@:

> The other issue is that the "combined feed" button is now hidden in a menu. I use it more often than the # and people button.
