### ISSUE TITLE
Handle edited messages (update_message events, 1/2)

### ISSUE THREAD

**Issue by gnprice** [zulip/zulip-flutter#118]
https://zulip.com/api/get-events#update_message

This issue is for the case where the message's contents were changed. (The case where the message changed stream and/or topic is #150.)

In particular these should be handled in the MessageListView view-model, so that the edits get reflected in a message list the user might be looking at.

For this issue, we'll:
* Add a new `Event` subclass for these events, similar to the others.
  * For this issue we can ignore `new_stream_id`, `propagate_mode`, and all the other properties that are documented at https://zulip.com/api/get-events#update_message as present only when the event moved messages. (We'll get to those later as part of #150.)
* Handle these events in `PerAccountStore.handleEvent` by calling a newly-added method on `MessageListView`, similar to the handling of `MessageEvent`.

**Comment by chrisbobbe** [comment]
Related issue: https://github.com/zulip/zulip-flutter/issues/118

**Comment by gnprice** [comment]
> Add a new `Event` subclass for these events, similar to the others.

This part is now done, as #212.

The remaining part of this issue is to handle the events.

**Comment by oxling** [comment]
👋 Hello! I'll take on the event handling.

**Comment by gnprice** [comment]
Sounds great! Marked on the issue metadata that you're taking it on.
