### ISSUE TITLE
Crash on launch on Galaxy S5

### ISSUE THREAD

**Issue by gnprice** [zulip/zulip-flutter#1189]
A user reports [in chat](https://chat.zulip.org/#narrow/channel/48-mobile/topic/Flutter.20app.20on.20Lineage.20OS.20crashes.20on.20opening/near/2005040):

> I just installed the Beta Version 0.0.24 on Lineage OS 18.1-20240219-microG-klte on a Samsung S5.
> Could not test much:
> The app installs from .apk without any visible issues but crashes when I try to open it.
> It just vanishes after showing a completely black screen for about a second.

They kindly set up ADB and got the crash dump from `adb logcat`; it reads:
```
2-17 09:18:57.979 25444 25479 F libc    : Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x34 in tid 25479 (1.raster), pid 25444 (m.zulip.flutter)
12-17 09:18:58.080 25492 25492 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
12-17 09:18:58.080 25492 25492 F DEBUG   : LineageOS Version: '18.1-20240219-microG-klte'
12-17 09:18:58.080 25492 25492 F DEBUG   : Build fingerprint: 'samsung/kltexx/klte:6.0.1/MMB29M/G900FXXU1CRH1:user/release-keys'
12-17 09:18:58.080 25492 25492 F DEBUG   : Revision: '14'
12-17 09:18:58.081 25492 25492 F DEBUG   : ABI: 'arm'
12-17 09:18:58.081 25492 25492 F DEBUG   : Timestamp: 2024-12-17 09:18:58+0100
12-17 09:18:58.081 25492 25492 F DEBUG   : pid: 25444, tid: 25479, name: 1.raster  >>> com.zulip.flutter <<<
12-17 09:18:58.081 25492 25492 F DEBUG   : uid: 10191
12-17 09:18:58.081 25492 25492 F DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x34
12-17 09:18:58.081 25492 25492 F DEBUG   : Cause: null pointer dereference
12-17 09:18:58.081 25492 25492 F DEBUG   :     r0  76d60e9c  r1  00000004  r2  00000000  r3  00000018
12-17 09:18:58.082 25492 25492 F DEBUG   :     r4  76d11828  r5  00000007  r6  76d11c40  r7  76d11a18
12-17 09:18:58.082 25492 25492 F DEBUG   :     r8  00000003  r9  00000078  r10 76d1100c  r11 771dfae8
12-17 09:18:58.082 25492 25492 F DEBUG   :     ip  00000013  sp  85f40420  lr  94712185  pc  946ed1a8
12-17 09:18:58.212 25492 25492 F DEBUG   : backtrace:
12-17 09:18:58.213 25492 25492 F DEBUG   :       #00 pc 000741a8  /system/vendor/lib/libsc-a3xx.so (BuildId: 6cc3e1de4bc187dc870459afd6a4c045)
12-17 09:18:58.213 25492 25492 F DEBUG   :       #01 pc 00073f59  /system/vendor/lib/libsc-a3xx.so (BuildId: 6cc3e1de4bc187dc870459afd6a4c045)
12-17 09:18:58.213 25492 25492 F DEBUG   :       #02 pc 00074127  /system/vendor/lib/libsc-a3xx.so (BuildId: 6cc3e1de4bc187dc870459afd6a4c045)
12-17 09:18:58.213 25492 25492 F DEBUG   :       #03 pc 001fe4e6  [anon:stack_and_tls:25479]
```

So the crash is in `libsc-a3xx.so`. From a bit of googling I believe that's a GPU driver.

I expect the story here will be similar to #941. I'll report an upstream issue.

**Comment by gnprice** [comment]
… Actually, it looks like this was already fixed upstream:
* https://github.com/flutter/engine/pull/57069
* in response to: https://github.com/flutter/flutter/issues/159834

The reason v0.0.24 doesn't have that fix is that it uses Flutter commit flutter/flutter@1c1f35711be76d1d2a9f5e3a730747591e64e14a, from Dec 8, and that fix happened the next day, Dec 9.

So this should get fixed in Zulip when we next upgrade Flutter, which we'll naturally do before our next beta release.

**Comment by gnprice** [comment]
That Flutter upgrade happened in #1184, so this should now be fixed.

(Once the next beta is out, including that update, we'll follow up with the reporter to confirm it's working for them.)

**Comment by jonahwilliams** [comment]
I saw this linked from that PR, but just to note that the Galaxy S5 does not support Vulkan nor does it have the right API level for Impeller (https://www.gsmarena.com/samsung_galaxy_s5-6033.php) so the crash is unlikely to be related.
