### ISSUE TITLE
Add `streams` to `PerAccountStore`, with a map keyed by stream ID

### ISSUE THREAD

**Issue by chrisbobbe** [zulip/zulip-flutter#136]
We should initialize this from the `streams` key in the initial snapshot (`InitialSnapshot`), and keep it updated in response to `stream` events.

**Comment by chrisbobbe** [comment]
Assigning Greg because he mentioned having a local branch that accomplishes this.

**Comment by gnprice** [comment]
My branch (which I'll send as a PR shortly) adds `InitialSnapshot.streams`, and adds a map on PerAccountStore, but doesn't add the event-handling to keep the map updated.

I think that's fine for the moment; it's how the subscriptions map already works. We can let #135 track the need to add event-handling to update this data.
