### ISSUE TITLE
msglist: Offer DM-conversation narrows

### ISSUE THREAD

**Issue by gnprice** [zulip/zulip-flutter#142]
Splitting this out from:
* #72 

because I have an implementation of the rest of that issue basically ready, but I'm finding that for DM/PM narrows there's a stack of related things I want to build or clean up first, so I'd like to decouple those in order to get the rest of it in.

All of those needed cleanups stem from the fact that a Zulip DM conversation is identified by a list of users, not a single crisp ID — opening up a range of possibilities for the exact format — and that the server API can be a bit chaotic about which format to use. (Compare `src/utils/recipient.js` in zulip-mobile.)

**Comment by chrisbobbe** [comment]
> All of those needed cleanups stem from the fact that a Zulip DM conversation is identified by a list of users, not a single crisp ID — opening up a range of possibilities for the exact format — and that the server API can be a bit chaotic about which format to use. (Compare `src/utils/recipient.js` in zulip-mobile.)

I think I'll be glad for those cleanups/constructs when it comes to writing DM links for quote-and-reply, #116. 🙂 (Note that our quote-and-reply code in zulip-mobile goes through that `src/utils/recipient.js` you mentioned.)

**Comment by gnprice** [comment]
Probably this should be preceded by:
* #145

since that will otherwise have to touch a bunch of the code this will add.
