### ISSUE TITLE
Say "DM" / "direct message" instead of "PM" / "private message", in code and UI

### ISSUE THREAD

**Issue by gnprice** [zulip/zulip-flutter#145]
This is a change that happened in the web UI a few weeks after I started prototyping the Flutter app:
* https://github.com/zulip/zulip/pull/24224

It's also happening in the server API, though necessarily more gradually. See summary at:
* https://github.com/zulip/zulip-mobile/issues/5725

The code still reflects the old name, in identifiers and comments. We should update it to the new name; this is easier to do the sooner we do it.

While we're at it, we should handle occurrences in UI text, too. I think the only one of these so far is in recipient headers.

Out of scope for this issue is to use the new name in the actual API, in the places where it's accepted. That's tracked as part of:
* #146

---

To find places to update, use the following search:
```
$ git grep -P 'pm|Pm|PM|(?i:private)' -- lib test
```
That currently finds 43 lines, of which it looks like
* 4 are in the API;
* 4 are false positives;
* so 35 are in scope for this issue.

**Comment by PIG208** [comment]
https://github.com/zulip/zulip-flutter/blob/1d24f6d526939e7d434b2eeccbf401c171232fed/lib/api/model/events.dart#L718-L724

It appears that there are some additional instances of "private" for `MessageType` used in some event models. Should we reopen the issue?

**Comment by gnprice** [comment]
Hmm indeed, thanks. Rerunning the search command above, there's also `InitialSnapshot.recentPrivateConversations`.

It looks like both that and `MessageType.private` were introduced after this issue was closed by #152.

I'll open a new issue for it — I think it'll be easier to track the revived issue that way, since this old one was fixed a year ago.
