### ISSUE TITLE
Track Zulip feature level on ApiConnection; use it

### ISSUE THREAD

**Issue by gnprice** [zulip/zulip-flutter#146]
This will let us do our part for server API migrations, by using the new API where available so that this client isn't a compatibility obstacle for future server versions to drop the old API.

In particular, this means:
* Say "direct" instead of "private" on `sendMessage`. (Compare https://github.com/zulip/zulip-mobile/issues/5725 .)
* Say "dm" instead of "pm-with" on `getMessages`.
* Scan the existing code for any other places where we're using an old API and can conditionally use a new one instead. These should already be marked with `TODO(server-…)` comments.

**Comment by gnprice** [comment]
(Once we've set this up once, it'll be easy to do the same thing along the way as we add more to the API bindings. So it's easiest if we do this early.)

**Comment by chrisbobbe** [comment]
This seems quite helpful for #140 (see discussion of FL 120+ condition there), which in turn will be useful for quote-and-reply #116. So the "Alpha" milestone seems appropriate. 🙂
