### ISSUE TITLE
ui: Distinguish `isBot: true` users with a bot marker

### ISSUE THREAD

**Issue by chrisbobbe** [zulip/zulip-flutter#156]
As Alex [points out](https://chat.zulip.org/#narrow/stream/48-mobile/topic/no.20marker.20for.20bots/near/1587460) about the zulip-mobile app:
> The mobile UI doesn't differentiate between bots and real humans in any way -- except clicking into the user profile and noticing the `-bot@chat.zulip.org` email address (though that page will also show them as a "member" which seems further confusing).  With the profusion of LLM bots running around, this can be moderately misleading to users.

We should implement this in the Flutter app.

The web app currently adds a little gray robot icon next to the user's name:

<img width="153" alt="image" src="https://github.com/zulip/zulip-flutter/assets/22248748/ed42e347-4037-442c-b2f0-a08ed056314f">

**Comment by gnprice** [comment]
Once we take care of #200, we'll have a straightforward way to pull in our own custom icons.

If we pick up this issue before then, we can instead just use one of the Material Design icons that Flutter makes convenient through [`Icons`](https://api.flutter.dev/flutter/material/Icons-class.html). Then this icon will just be one of the icons that we sweep through and replace as part of  #200 or a followup.

**Comment by sm-sayedi** [comment]
I would like to take this one!

<img src="https://github.com/zulip/zulip-flutter/assets/59946442/7a99bd7e-3d36-4b53-859c-6c86020987ad" width="300" />
