### ISSUE TITLE
Try using same fonts in content as Zulip web 

### ISSUE THREAD

**Issue by gnprice** [zulip/zulip-flutter#163]
This is a continuation of #64. That issue was about both an experiment to do to exercise features of Flutter, and a user-facing change to try in the app. We did the experiment and closed the issue, but the user-facing change remains open.

Adapting that issue's description:

Zulip web uses the font Source Sans 3 for most text, and Source Code Pro for code blocks and code spans.

Currently, in much of zulip-flutter as well as in the zulip-mobile RN app, we use system fonts. This has advantages but also disadvantages:

* [Bundle a font in the app and use it consistently zulip-mobile#2447](https://github.com/zulip/zulip-mobile/issues/2447)
* [Solution found: Newer Unicode emojis don't render on older Android devices zulip-mobile#3885](https://github.com/zulip/zulip-mobile/issues/3885)

Since #94, we use Source Code Pro for code blocks and code spans, but continue to use system fonts for the rest of the text.

It would be neat to try using the same fonts as on web, for the entire content of messages. Probably for the rest of the message list too: recipient headers, dates, etc.

**Comment by chrisbobbe** [comment]
I think this issue is fixed:

- For code blocks: #94
- For all other content: c7be9c34de20f08f95aff40ccb741f193fbbaaa4

This bit isn't yet taken care of:

> Probably for the rest of the message list too: recipient headers, dates, etc.

But I assume it will be naturally when we address

- #157

.

So, closing.
