### ISSUE TITLE
Star and unstar messages; show starred status

### ISSUE THREAD

**Issue by gnprice** [zulip/zulip-flutter#170]
This Zulip feature:
https://zulip.com/help/star-a-message

Out of scope for this issue is to show a message list for the narrow consisting of starred messages. We'll file a separate issue for that.

**Comment by terpimost** [comment]
The basic idea here is Long tap > Star message > show icon on the right gutter (the same as in desktop zulip)
After that we could think of something better (swipe the message to a side to see buttons like iOS does)

**Comment by gnprice** [comment]
Cool, that sounds good. That long-tap interaction is the same as we currently have in zulip-mobile, then.

For the icon in the right gutter, is the current design in Figma all set, or are there any updates you'd like to make from that?
