### ISSUE TITLE
Push PerAccountRoot under MaterialApp, into each individual page widget

### ISSUE THREAD

**Issue by gnprice** [zulip/zulip-flutter#21]
This will let us have a single MaterialApp that can navigate between pages that are for different accounts, as well as pages like the login flow and account-switch UI that are for no particular account at all. That makes it a necessity for doing #11 in a reasonable way.

One part of this will be to let the PerAccountRoots for a given account all point to a single PerAccountStore. That's this TODO from #20 which I just sent:
```dart
  // TODO add a registry of [PerAccountStore]s, like the latter's of [MessageListView]
  //   That will allow us to have many [PerAccountRoot] widgets for a given
  //   account, e.g. at the top of each page; and to access server data from
  //   outside any [PerAccountRoot], e.g. for handling a notification.
```

The other part to take care of will be arranging that the API we provide for ourselves to use when we're adding new routes, and navigating to routes, isn't too annoying or error-prone. I have some thoughts and we'll see how it looks after I experiment.

**Comment by Sudhanva-Nadiger** [comment]
HI @gnprice if possible please add a contributing.md file, so that we can lean how do we contribute to this repo. Thanks

**Comment by gnprice** [comment]
@Sudhanva-Nadiger Because the code in this repo is an experimental prototype, it isn't really set up to welcome new contributors in the way the Zulip project does in general. See [the Zulip contributing guide](https://zulip.readthedocs.io/en/latest/contributing/contributing.html) for help contributing to Zulip.

In any case, that has nothing to do with the issue this thread is about. So for any further discussion, let's use chat in the Zulip development community; see that guide for a link.
