### ISSUE TITLE
Ellipsize narrow description in app bar for message list

### ISSUE THREAD

**Issue by gnprice** [zulip/zulip-flutter#221]
In the app bar for the message list, we describe the narrow you're looking at: the stream and topic, or list of DM recipients, etc. That can easily be too much text to fit, and in that case we just run off the end. Here's how that looks in debug mode with its warning stripes:
![image](https://github.com/zulip/zulip-flutter/assets/28173/114ceaff-299e-4da0-94be-edd7a8d12b9e)

Instead, we should bound the width to fit and ellipsize the text.

A similar issue applies to the recipient headers, but less severely: there's more room there, and a smaller font size (body-text size instead of a big title size), so the overflow is much less common.

**Comment by ShivamMenda** [comment]
Hey @gnprice I was wondering wether I could work on this if it's open to take up?

**Comment by gnprice** [comment]
This issue no longer reproduces; it looks like we just neglected to close this issue thread.

(Specifically, both the app bar and the recipient headers ellipsize properly when the topic name is long.)

@ShivamMenda Please take a look at the Zulip project's guidance for [picking an issue to work on](https://zulip.readthedocs.io/en/latest/contributing/contributing.html#picking-an-issue-to-work-on). In this repo we don't have the "help wanted" label because this codebase isn't yet fully set up to welcome contributors; but that just makes the other steps all the more important.
