### ISSUE TITLE
Add Font Awesome icons

### ISSUE THREAD

**Issue by gnprice** [zulip/zulip-flutter#222]
In Zulip web we use Font Awesome for many of the icons in the UI. We should pull in an appropriate dependency so we can start using the same icons in zulip-flutter. (This is a sort of followup to #200.)

This package seems appropriate and popular:
https://pub.dev/packages/font_awesome_flutter

One concrete place we could use such an icon is in the title of the "All messages" narrow:
https://github.com/zulip/zulip-flutter/pull/219#discussion_r1267326238

**Comment by terpimost** [comment]
I don't suggest to adopt any font awesome icons at all

**Comment by gnprice** [comment]
Cool, thanks. In that case I guess we can close this issue. It'll always be here as a reference in case we later decide for some reason we do want some such icons after all.
