### ISSUE TITLE
Disable vscode autoformatting

### ISSUE THREAD

**Issue by gnprice** [zulip/zulip-flutter#229]
We've had a couple of contributors who use Visual Studio Code, and were frustrated by its eagerness to reformat entire files:
* https://github.com/zulip/zulip-flutter/pull/224#issuecomment-1642472497
* https://github.com/zulip/zulip-flutter/pull/155

It should be possible to supply project-level config to VS Code to tell it not to do that, and we should put that config in the repo.

The PR #155 included a draft of such a config, which can be a starting point.

**Comment by onli** [comment]
A suggestion: The ideal solution would be not to disable the formating completely, but to let that IDE autoformat it in an acceptable way. I'm actually surprised that there is a format conflict here, doesn't VSCode with the flutter plugin just call dartfmt, and wouldn't dartfmts default be the best code style for this flutter project?

**Comment by gnprice** [comment]
Yeah. We don't use dartfmt, and instead use a style similar to what's in the Flutter repo itself:
https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#formatting

Our experience has been that
* there are several recurring ways in which dartfmt tends to make the code harder to read than it would be if formatted better;
* and at least for me, when using dartfmt / `dart format`, it hasn't felt to me like it means not thinking about formatting, more like doing different thinking about formatting.

Discussion with more details here:
https://chat.zulip.org/#narrow/stream/48-mobile/topic/Dart.20formatting/near/1585603

The Flutter folks would like to use autoformatting too, and have had discussions for years with the Dart folks about making dartfmt work well for the Flutter style. I recently saw a mention that there might be progress happening on that, which would be great.
