### ISSUE TITLE
Track unread counts

### ISSUE THREAD

**Issue by gnprice** [zulip/zulip-flutter#253]
We want to show how many unread messages the user has in each stream and conversation, how many unread @-mentions they have, and how many unreads they have total, each in various places in the UI.

The data to power this begins with the `unread_msgs` data structure in the initial data — search for "unread_msgs:" in https://zulip.com/api/register-queue . It then needs to be updated on a variety of events: new message, messages marked read or unread, messages moved or edited (affecting @-mention status), message deleted, and some others.

In zulip-mobile, this is tracked as `state.unread`. See [src/unread/unreadModel.js](https://github.com/zulip/zulip-mobile/blob/c979530d6804db33310ed7d14a4ac62017432944/src/unread/unreadModel.js) and [src/unread/unreadSelectors.js](https://github.com/zulip/zulip-mobile/blob/c979530d6804db33310ed7d14a4ac62017432944/src/unread/unreadSelectors.js). The handling there of counts for DMs and @-mentions (and the overall total) is legacy and isn't to be imitated, but the handling for streams and stream conversations — typically the bulk of the data — was overhauled more recently and much of that should translate well.

Then this data should appear in the UI:
* in the list of recent DM conversations #119
* in the inbox view #117 
* in the stream list #187
* on a button to navigate to the @-mentions narrow #250
* probably in the between-organization navigation
* perhaps other places

For any of those pieces of UI that we've already implemented when we take up this issue, we can add the data to those parts of the UI as part of this issue. For the rest, we can include this data when we first implement those parts of the UI.

**Comment by chrisbobbe** [comment]
Tentatively milestoning this as "alpha"; feel free to change.

**Comment by gnprice** [comment]
> Then this data should appear in the UI:
> 
> * in the list of recent DM conversations [ui: Add list of recent DM conversations #119](https://github.com/zulip/zulip-flutter/issues/119)

I've forked this part off as a followup issue:
* #328 

So we can close this issue when we complete the model, and use that one to track the remaining task of adding it to the UI there.

**Comment by gnprice** [comment]
This was completed when we merged #304.
