### ISSUE TITLE
msglist: In "All messages", content and the scroll-to-bottom button render in iOS bottom inset

### ISSUE THREAD

**Issue by chrisbobbe** [zulip/zulip-flutter#263]
| At bottom | Not at bottom (scroll button visible) |
| --- | --- |
| ![665ADFE7-9A05-4BE5-8DF3-66F04CFEAF56](https://github.com/zulip/zulip-flutter/assets/22248748/70480a3e-a1c4-4d5c-911d-52f03125d07a) | ![77BCA164-EC03-4D6A-9EF5-2F61CB456DB3](https://github.com/zulip/zulip-flutter/assets/22248748/542d6ca0-9b05-453f-9e03-d55346b1673a) |

Hmm, iOS's "screenshot" feature doesn't actually show the rounded hardware corners, but those can be imagined, or I could use macOS's screenshot feature to capture an iOS device simulator.

But also, from reading code, one can see that the bottom inset isn't accounted for in the all-messages view.

This will be naturally solved if we put some surface down there that pads the bottom inset, with the message list abutting that surface in the y-direction. That surface is likely to be the bottom nav bar in Vlad's design, I think.

**Comment by gnprice** [comment]
Hmm, good catch, thanks!

I initially applied the Alpha milestone, but then thought again about the fact that it only applies in narrows that don't show a compose box. I think that makes this bug tolerable for an alpha, so I'll move it to the Beta milestone.
