### ISSUE TITLE
Open links in-app by default on Android, once that has a good UX

### ISSUE THREAD

**Issue by gnprice** [zulip/zulip-flutter#279]
When opening an external link, we have a choice whether to do so within the app or in an external browser.

Currently we do so following the upstream Flutter defaults ([documented at launchUrl](https://pub.dev/documentation/url_launcher/latest/url_launcher/launchUrl.html)), except that on Android we always use an external app rather than the in-app browser. That's because Flutter's implementation of the latter is currently not a good UX:
* https://github.com/flutter/flutter/issues/18589#issuecomment-1681590394

Once that's fixed, I think it'd be best to default on Android to opening in-app, just as the Flutter `url_launcher` plugin defaults to. That's what we chose on zulip-mobile, for reasons discussed [in this chat thread](https://chat.zulip.org/#narrow/stream/48-mobile/topic/in-app.20browser/near/1169095), and I think all the same reasoning still applies.

Separately:
* We should offer an option (again just as we do in zulip-mobile), so that this is only about the default. That's part of #97.
* On iOS our choice in zulip-mobile was to default to an external app, unlike on Android. That reasoning is in the same thread and again I think it all still applies. That differs from the `url_launcher` default, so we should adjust that: #280

**Comment by gnprice** [comment]
Milestoning as post-launch based on the scenario where it falls to us to fix the upstream issue. But if someone else picks up that upstream issue and fixes it sooner, then what's left of this issue will be an easy tweak and we should go ahead and do it.

**Comment by rajveermalviya** [comment]
I opened flutter/packages#4739 which uses Android Custom Tabs support when `launchUrl` is called with `LaunchMode.externalApplication`. 
So, after that is maybe merged we can change to use that.
