### ISSUE TITLE
profile: Display email

### ISSUE THREAD

**Issue by sirpengi** [zulip/zulip-flutter#291]
In the profile screen (#195 ) we need to show the user's email address if it is accessible, but not the fake email that Zulip creates for the api.

Also need to handle the user update event for `null` values of `delivery_email` appropriately.

Helpful links:
- Search for "delivery_email:" in https://zulip.com/api/get-events#realm_user-update
- `getDisplayEmailForUser` in zulip-mobile: https://github.com/zulip/zulip-mobile/blob/8133bf2b8/src/users/userSelectors.js#L318

**Comment by MrunalrajRedij** [comment]
Hey, If it is not already fixed. Can I work on this issue?

**Comment by gnprice** [comment]
@MrunalrajRedij Please take a look at our guide for picking an issue to work on:
https://github.com/zulip/zulip-flutter#picking-an-issue-to-work-on

**Comment by gnprice** [comment]
> Also need to handle the user update event for `null` values of `delivery_email` appropriately.

This is accomplished by #F784. So once that's merged, `User.deliveryEmail` can be used normally.
