### ISSUE TITLE
Request avatars of the appropriate size

### ISSUE THREAD

**Issue by chrisbobbe** [zulip/zulip-flutter#301]
With #195 fixed with PR #287, we now have a user-profile screen! 🎉

I noticed that on many profiles on CZO, the avatar is more blurry than on the corresponding screen in `zulip-mobile`:

| zulip-flutter | zulip-mobile |
| --- | --- | 
| ![image](https://github.com/zulip/zulip-flutter/assets/22248748/66896560-9b27-4f0d-813d-2164e7aaafca) | ![image](https://github.com/zulip/zulip-flutter/assets/22248748/644603ff-c376-45b4-b50e-dc0f0d1839bc) |

This is because we don't yet have special logic for requesting a larger image when we need one. This issue is for adding such logic.

In `zulip-mobile`, we made an `AvatarURL` class with a `get` method that gives you a URL for an image of the specified size in physical pixels (or at least the best possible approximation). `AvatarURL` has [three subclasses](https://github.com/zulip/zulip-mobile/blob/09754f0a5d7408fd490a631339eced3cf77a28e0/src/utils/avatar.js) that each implement `get` very differently.

On CZO in `#api documentation`, I've [summarized](https://chat.zulip.org/#narrow/stream/412-api-documentation/topic/avatar_url.3A.20Request.20specific.20size/near/1636546) zulip-mobile's logic for determining a URL for any given size in physical pixels. I'm hoping the API doc can start specifying that logic, and we can use the new documentation for zulip-flutter's implementation.

To convert a logical-pixel value to a physical-pixel value, we'll want to multiply by the device pixel ratio. As in zulip-mobile:
```js
avatarUrl.get(PixelRatio.getPixelSizeForLayoutSize(size))
```

I think a solution will likely have lots of interactions with #254 and #255, so the best approach might be to consider these three issues together.

Related: #254
Related: #255

**Comment by chrisbobbe** [comment]
An observant user noticed the blurriness and reported it in chat today: https://chat.zulip.org/#narrow/stream/48-mobile/topic/flutter.3A.20blurry.20profile.20picture/near/1735359

**Comment by saisumith770** [comment]
@gnprice I'm currently working on this feature. Finished with most of the task using gravatar's. I would like to know which formatter you are using because as I save my code most of the file gets re-formatted causing several changes in the git history. It would be really helpful if you linked the contributing guidelines as well.

**Comment by gnprice** [comment]
@saisumith770 Cool — assigned you the issue, and I'll look at your PR in the next few days.

We don't use an auto-formatter, so you'll want to just tell your editor not to do that. Let's discuss in `#mobile-team` on chat.zulip.org.

For contributing guidelines, this repo's README file has information on running tests and making changes. We also follow the same basic style of clean commit history as the Zulip project in general, which is described here:
https://zulip.readthedocs.io/en/latest/contributing/commit-discipline.html
