### ISSUE TITLE
Overall app navigation for beta

### ISSUE THREAD

**Issue by gnprice** [zulip/zulip-flutter#311]
In the current implementation, the way you get to the various screens (like the "All messages" narrow and the list of DM conversations) is from a "home page" that just has some buttons. It's a consciously prototype-level UI.

One reason we've stuck with that so far is that we don't yet have all the major screens that would naturally belong in an overall navigation for the app. The two still open now are:
* #187 
* #117

For the beta, we should have some more presentable answer. Probably the home screen should be the inbox view #117, rather than a bunch of nav buttons; the navigation then has to go someplace else.

A first answer would be to copy the navigation we have in zulip-mobile, with bottom tabs. We also have some designs for an overhaul of the app's navigation. Given the beta timeline, we may not be able to iterate on those and integrate them for the beta, but we can revisit them for the next stage.

**Comment by gnprice** [comment]
The discussion above (in the issue description) is focused on the navigation between different screens for dealing with a given account. For probably most users, there's only one account they use and so this is the whole story.

But because for some users it is essential to use multiple accounts — not least, for us developers as we use test accounts and test servers as well as our own main accounts — we'll always need some reasonable way to switch between accounts and to add a new account. So that should be part of our navigation thinking too.

The current solution, which we've had since very early in the prototype, is that the app opens showing the choose-account screen, and you can tap an account from there to start loading data for that account. This works, but it's a bit of an extra step when starting the app, and for users who have just one account it may feel unnecessary.

It'd be good to instead go straight to the account you were last using. But in order to do that, we'll need some other place in the UI for you to get to other accounts. See [chat discussion](https://chat.zulip.org/#narrow/stream/48-mobile/topic/zulip.20flutter.20login.20screen/near/1714661).

**Comment by c-o-d-e-y-o-d-a** [comment]
Hello there, has the issue  "option to choose home view.." been assigned to someone yet? I would like to work on this.

**Comment by gnprice** [comment]
@c-o-d-e-y-o-d-a That issue has its own thread, #517. Discussion of it should go there, or in Zulip.

If you'd like to work on that issue (or another issue), please see the Zulip project's guide to "where to look for an issue", picking an issue, and claiming an issue:
https://zulip.readthedocs.io/en/latest/contributing/contributing.html#your-first-codebase-contribution

**Comment by gnprice** [comment]
I've just written up a detailed spec for this task (borrowing from a [previous writeup by Alya](https://chat.zulip.org/#narrow/channel/243-mobile-team/topic/UI.20redesign.3A.20root.20level.20nav/near/1905990)):
* #1035 

Closing this issue in favor of that fresh thread.
