### ISSUE TITLE
RecentDmConversationsPage: Breaks with nonzero horizontal device insets

### ISSUE THREAD

**Issue by chrisbobbe** [zulip/zulip-flutter#339]
Such as on an iPhone 15 Pro in landscape mode. Seen here in a simulator, with the not-yet-merged unread counts from #334. I'm long-pressing to show how the row responds:

<img width="1011" alt="image" src="https://github.com/zulip/zulip-flutter/assets/22248748/08237874-84a6-44d8-a1c1-b80014366550">

<img width="1010" alt="image" src="https://github.com/zulip/zulip-flutter/assets/22248748/d48271f7-417e-4d8f-b1e6-825bda2170b3">

**Comment by chrisbobbe** [comment]
Labeling "a-design" because I'm not sure how best to handle device insets for screen content like this.

cc @alya @terpimost

I see basically two approaches to solve this. (In these screenshots I'm also long-pressing a row; not sure why I don't get the circle these times.)

1. Have each row extend out to the edge of the screen and pad the insets; something like this:

<img width="1204" alt="Screenshot 2023-10-26 at 2 26 39 PM" src="https://github.com/zulip/zulip-flutter/assets/22248748/2d90269f-0715-4085-a181-7016f303f335">

2. Add a container around the whole list and have it pad the insets; something like this:

<img width="1208" alt="Screenshot 2023-10-26 at 2 23 09 PM" src="https://github.com/zulip/zulip-flutter/assets/22248748/f0ba438b-4578-429e-9fff-49ca729c5dd8">

**Comment by chrisbobbe** [comment]
A note about the screenshots in my previous message. On the side opposite the iPhone's black oval (for the camera), there's maybe more space than seems necessary. But that's just what happens when we faithfully follow the measurements iOS gives us for the horizontal insets. (Maybe they want to reserve so much room because of the large border radius on the corners of the screen itself.)

**Comment by gnprice** [comment]
Good question. My inclination would be for option 2. Is there another app or two where you can conveniently provoke the same situation and see how they handle it?

**Comment by chrisbobbe** [comment]
Gmail on iPhone is mixed; here are some screenshots. Unfortunately you'll have to imagine my phone's rounded corners and the camera notch, which don't show up in its take-a-screenshot feature. This is on my iPhone 13 Pro.

They do option 1:

![7101056F-1679-4E9B-8DF9-3AF822FCC879](https://github.com/zulip/zulip-flutter/assets/22248748/cd89f15e-7e94-4c29-ac36-dd2a572a9e54)

They do option 2:

![ABFEF08A-83EC-4DA5-A100-08FE649EABC1_1_201_a](https://github.com/zulip/zulip-flutter/assets/22248748/5cce165d-6fff-4355-9604-ce7f1433e4d3)

And they do a better (I think) version of option 2 where the area covered by the ink effect is also visible when you're not pressing a row, as a nice surface with rounded corners:

![588C3091-E1C5-4E6B-AB4D-1B03C9BE3802](https://github.com/zulip/zulip-flutter/assets/22248748/e9b8f2ca-04c9-4118-88b3-d239fb0d19b9)

**Comment by chrisbobbe** [comment]
Wikipedia on iPhone—in lists like these—seems to prefer option 1 consistently. It has some bugs where some content fails to position outside the insets:

![46B3C3D0-A9C5-48AF-BE3D-D0F9406273C8](https://github.com/zulip/zulip-flutter/assets/22248748/5834efcd-d3f8-40f4-8d68-fcf317d1e708)

![68D29104-AFCA-4466-89D0-A39B41B68085](https://github.com/zulip/zulip-flutter/assets/22248748/a015e96e-bde2-461d-80df-afc8c8a32631)

(see "Add another language", and the line under it, are outside the safe area)

**Comment by gnprice** [comment]
Cool, thanks. I guess those are inconclusive, then, and I'd still incline toward option 2 pending input from @terpimost.

> version of option 2 where the area covered by the ink effect is also visible when you're not pressing a row, as a nice surface with rounded corners:

I think this works well in that settings screen, where there's several sections and they each have a heading above them. On this screen, though, I think the rounded effect would look odd at the top and bottom of the list.

**Comment by terpimost** [comment]
In my design buttons have rounding corners, and there is always a gap between edge of a screen, so in cases when you have safe area it shouldn't be a problem... I do suggest to don't support landscape mode.

I don't assume we have material UI components and their tap animations... I suggest to not bring it to iOS version at least.
I think it is ok to darken the hit area or a button on tap. We can also scale down the button a bit as a default option. It is also ok to not bother for the smaller elements which user might not even see under the finger.

**Comment by gnprice** [comment]
> I don't assume we have material UI components and their tap animations... I suggest to not bring it to iOS version at least.

Cool, I've filed #417 for that. I've milestoned it for Beta 3, i.e. for the first beta that goes to a wider audience beyond chat.zulip.org.



> I do suggest to don't support landscape mode.

(This now has [a chat thread](https://chat.zulip.org/#narrow/stream/48-mobile/topic/landscape.20mode/near/1689267), following discussion on the PR #413.)
