### ISSUE TITLE
UI for topic muting/unmuting/following

### ISSUE THREAD

**Issue by gnprice** [zulip/zulip-flutter#348]
This will be a followup from #346, and a complement to #347.

In zulip-mobile, we offer this only for muting and unmuting — we haven't implemented the new "follow topic" feature. At a minimum, for launch, we should offer the same level of functionality as zulip-mobile; but then probably one of the first features we'd want to add after launch would be full "follow topic" support, so we might build the full version in the first place.

In zulip-mobile, we offer this in one place, the "topic action sheet", which you get by long-pressing a topic:
* as the app bar of a topic narrow;
* as the recipient header of a stream message in the message list;
* in the screen with the list of topics for a stream;
* in the inbox view.

We should do something broadly comparable, unless we do leap ahead to include "follow topic" support. We might in any case vary the details; for example if you long-press the stream name within a recipient header, that should perhaps give the stream action sheet instead of the topic action sheet.

**Comment by PIG208** [comment]
[Topic following in zulip-mobile](https://github.com/zulip/zulip-mobile/issues/5771) was added on Nov 22, 2023. To offer the same level of functionality, we should probably implement following as well.

**Comment by PIG208** [comment]
See [discussion](https://chat.zulip.org/#narrow/channel/48-mobile/topic/Adding.20user.20topic.20visibility.20markers.20.28muted.2C.20default.2C.20etc.2E.29/near/1969293) here on the design of this feature.
