### ISSUE TITLE
Handle `<hr>` horizontal lines

### ISSUE THREAD

**Issue by gnprice** [zulip/zulip-flutter#353]
We should handle the `<hr>` element.

This element means a "thematic break", shown as a dividing line; the name stands for  "horizontal rule". It's the result of a `---` line in Markdown.

Handling these means parsing them in `lib/model/content.dart`, and then styling them appropriately in `lib/widgets/content.dart`. For appropriate styling, see the Zulip web app's `web/styles/rendered_markdown.css`.

**Comment by jassirr** [comment]
@gnprice @chrisbobbe can I take this one up?

**Comment by jassirr** [comment]
@gnprice @chrisbobbe any update?

**Comment by Khader-1** [comment]
Instructive, but I imagine having the link to [web/styles/rendered_markdown.css](https://github.com/zulip/zulip/blob/main/web/styles/rendered_markdown.css) would give more context for readers.
Anyways, I am working on it!

**Comment by gnprice** [comment]
Seen by a beta user: [chat thread](https://chat.zulip.org/#narrow/stream/48-mobile/topic/Flutter.20app.20.2B.20SAML.20auth/near/1773998).
