### ISSUE TITLE
login: Support web-based auth methods

### ISSUE THREAD

**Issue by gnprice** [zulip/zulip-flutter#36]
I expect the first iteration of a login flow #11 will offer only email/password auth. We should add support for the rest.

In particular this means web-based auth, which covers Google auth and GitHub auth among others. ~~We can split out other methods as separate issues, if we don't find they're easy to just do at the same time.~~ Other forms of auth are tracked separately:
* #405 
* #462

**Comment by chrisbobbe** [comment]
For Apple, there's a "Flutter Favorite" plugin [`sign_in_with_apple`](https://pub.dev/packages/sign_in_with_apple).

Probably it makes sense to start with Apple; as I recall, they'll reject apps in App Store review if they have third-party auth but no Apple auth.

**Comment by chrisbobbe** [comment]
We should remember that although [`authentication_methods`](https://zulip.com/api/get-server-settings#response) is marked in the doc as deprecated in 2.1.0, it still seems necessary for writing a correct client. Discussion: https://chat.zulip.org/#narrow/stream/412-api-documentation/topic/audit.20for.20change.20entries.20vs.2E.20central.20changelog/near/1404115

**Comment by gnprice** [comment]
> For Apple, there's a "Flutter Favorite" plugin [`sign_in_with_apple`](https://pub.dev/packages/sign_in_with_apple).

Good to know, thanks.


> Probably it makes sense to start with Apple; as I recall, they'll reject apps in App Store review if they have third-party auth but no Apple auth.

That means we'll need Apple auth before a full launch, or even an open beta in the form of an alternate app in the App Store. But I think we'll need web-based auth before that milestone, too, because lots of people rely on that.

One thing that could cause us to prioritize web-based auth or any other auth method sooner than that milestone is if it's an obstacle for a significant number of users who might join an earlier stage of the beta. I think that's unlikely for Apple auth, because I suspect not many people are using it, but is more likely for web-based auth because of people using Google or GitHub auth.

**Comment by gnprice** [comment]
I've split this issue up, as foreshadowed in the original description, and edited the description accordingly.

**Comment by gnprice** [comment]
@fizy069 Hello, welcome!

This will be a complex issue partly because of the several different APIs the implementation needs to integrate with, and partly because it's security-sensitive and so requires an especially close review and a high level of making the code and commits clear so they're easy to review. So it won't be a good fit for one of the first few issues in Zulip to work on.

Instead, take a look at our [project board](https://github.com/orgs/zulip/projects/5/views/4) for the app, and try browsing through the issues that are in the "Beta 2" or "Beta 3" milestones but don't have anyone already assigned. Many of those would be good issues to start with.
