### ISSUE TITLE
api: Make a structured exception type for API errors, and use it

### ISSUE THREAD

**Issue by gnprice** [zulip/zulip-flutter#37]
Like the `ApiError` and its base class `RequestError` that we have [in the RN app in `src/api/apiErrors.js`](https://github.com/zulip/zulip-mobile/blob/58541b6c9fa25d457d00aae0a6f4c4ef18a5b0bb/src/api/apiErrors.js).

**Comment by chrisbobbe** [comment]
Some API errors indicate a condition that's basically fatal to the current API connection: the user's auth credential was invalidated, the realm or user was deactivated (see zulip/zulip-mobile#4571), possibly more. (Maybe the invalid-event-queue error?)

I wonder if we need to think about those differently than more mundane API errors, like when you tried to send a message with a too-long topic.
