### ISSUE TITLE
Handle subscription peer add/remove events

### ISSUE THREAD

**Issue by sirpengi** [zulip/zulip-flutter#374]
Part of #135 

https://zulip.com/api/get-events#subscription-peer_add
https://zulip.com/api/get-events#subscription-peer_remove

This issue is for handling when subscribers on a subscription are being modified. `subscription op:add`, `subscription op:remove` and `subscription op:update` are being handled as part of #187

**Comment by gnprice** [comment]
These events will become relevant only in a future where we start tracking the data that they update, namely the list of other subscribers to each channel.

If we do add such a data structure, we'll naturally go and handle the events that update it; that's the pattern for implementing new pieces of the Zulip data model in general. So I think there isn't an independent task to be tracked here, and isn't a need for this issue to track it.

Instead, if at some point we decide to add a feature that would use that data, we'll file issues as needed to describe what that feature needs.
