### ISSUE TITLE
inbox: On collapsing a section from its sticky header, auto-scroll as needed to put the collapsed header in view

### ISSUE THREAD

**Issue by chrisbobbe** [zulip/zulip-flutter#391]
In the inbox, if you've scrolled down several screenfuls through a section (either the all-DMs section or a stream section), you can still collapse the section by tapping the collapse icon on the stream header.

But when you do that, something confusing happens: everything that was below the last item in the section (which may or may not be onscreen) gets shifted upward by the whole vertical space that used to be occupied by the section. Since you'd been scrolling so much, the shift ends up putting some content offscreen in the upward direction. That's confusing because you might have been interested in that content, and skipping over it wasn't part of your intention when you collapsed a section that was unrelated to the content.

In this screen recording, the scenario happens multiple times in a row, with `#issues`, `#design`, and then `#development help` taking its turn to be the section that's partly scrolled through, and getting its sticky header tapped to collapse it.

![Nov-17-2023 23-52-59](https://github.com/zulip/zulip-flutter/assets/22248748/1e573dc8-6cc3-40a5-9e9d-60aaeea585c3)

I think the confusion would disappear if, when you press the sticky-header's collapse icon, we ensure that the collapsed header (the one that always moves, not the sticky one) is entirely visible on the screen, by changing the scroll position. We can try using something like [`Scrollable.ensureVisible`](https://api.flutter.dev/flutter/widgets/Scrollable/ensureVisible.html) for that. That way you can see that the section was collapsed, as intended, and the start of the next section is immediately below it and easy to start reading.

**Comment by sm-sayedi** [comment]
I would like to work on this issue. 

So far, I have partially solved it as below:

<img src="https://github.com/zulip/zulip-flutter/assets/59946442/c09b17cf-8311-4a0a-9bc4-47cdc9d901d7" width="300" />

**Comment by gnprice** [comment]
@sm-sayedi Sure — please send along your code for this as a PR and we'll be glad to take a look. From what I see in your screencast, the behavior looks like what we want.
