### ISSUE TITLE
Try bundling an emoji font

### ISSUE THREAD

**Issue by gnprice** [zulip/zulip-flutter#404]
Since #403, we don't bundle a font for emoji; instead we rely on the system fonts for showing Unicode emoji. This has advantages but also disadvantages:
* zulip/zulip-mobile#3885

The reason that since #403 we don't bundle a font is that we haven't found a good emoji font that works in Flutter on iOS, and although the one we were shipping seems to largely work on Android it's not clear it always does. Specifically there's this upstream issue:
* https://github.com/flutter/flutter/issues/134897#issuecomment-1821594910

and the symptom when it doesn't work is that using the font produces a blank space, even when the system font would have handled the emoji just fine.

If that upstream issue gets fixed, then we should be able to just resume shipping Noto Color Emoji in its COLRv1 form.

**Comment by chrisbobbe** [comment]
We learned at https://github.com/flutter/flutter/issues/134897#issuecomment-1821632095 that COLRv1 fonts aren't supported on any version of iOS. I think that means Noto Color Emoji just isn't usable on iOS.

So when we go back to bundling Noto Color Emoji, we should do so on Android only. That'll need

- https://github.com/flutter/flutter/issues/96514

or perhaps

- https://github.com/flutter/flutter/issues/21682

; I'm not really sure what the difference is. (That latter issue has a PR that's being actively worked on.)

**Comment by gnprice** [comment]
> I'm not really sure what the difference is.

Yeah, I'm not either. I left a comment https://github.com/flutter/flutter/issues/96514#issuecomment-1828637086 on the less-trafficked issue asking for clarification on how it differs.

**Comment by gnprice** [comment]
Even after that PR lands, it might still be somewhat annoying to have the asset just on one platform, because it looks like it doesn't directly support selecting by platform. It would make it possible to do so but only through a workaround: define a "flavor" to control including the font, and then use the no-emoji-font flavor when building releases for iOS.

An alternate solution would be to ship the font unconditionally, but only invoke it on Android; so it'd be in the iOS app bundle but wouldn't get used. I think that'd be fine through the beta period.

(This issue is currently milestoned post-launch, but given what we've discovered in trying to lay out reaction emoji just right — https://github.com/zulip/zulip-flutter/pull/410#discussion_r1402812415 — we might move it forward.)

**Comment by gnprice** [comment]
We closed this in #436, which bundles Noto Color Emoji again and uses it in part of the app. We've split out a new issue:
* #438

for using it in the rest of the app.
