### ISSUE TITLE
Update message list on muting/unmuting a stream or topic

### ISSUE THREAD

**Issue by gnprice** [zulip/zulip-flutter#421]
In my first implementation of stream and topic muting #346, I intend to leave in place one missing form of event update: if you have a message list you're already looking at (or already on the navigation stack), and then you mute or unmute a stream or topic so that it should cause some messages to disappear or appear in that message list, it won't notice that it should update.

This isn't fundamentally hard — just requires a bit of wiring up of the information — but it'll be a little bit of refactoring, and there's already enough refactoring going on in my draft for #346 that I'd like to keep the complexity down for now.

We don't yet offer UI within the app for muting or unmuting streams and topics (that's #347 and #348), so it won't currently be easy to actually run into this issue.

**Comment by chrisbobbe** [comment]
Unsubscribing from a stream means clearing out its mute state (`isMuted` is stored on the subscription). I wonder if that means message lists should also sometimes update on `SubscriptionRemoveEvent`s.

I don't think it's possible for a stream to be muted at the time you subscribe to it; i.e., the subscription has `isMuted: true` in the `SubscriptionAddEvent`. But if it is, we should handle that too.

**Comment by gnprice** [comment]
> I wonder if that means message lists should also sometimes update on `SubscriptionRemoveEvent`s.

Yeah, seems right. Filed that as #821.

**Comment by chrisbobbe** [comment]
#822 didn't handle updating the message list on muting/unmuting a channel, and it looks like that's still unhandled. 🙂 I've opened #1255 to revive the channel part of this issue.
