### ISSUE TITLE
Show muted streams as faded in streams list

### ISSUE THREAD

**Issue by gnprice** [zulip/zulip-flutter#424]
This is a followup to #346. We have all the relevant data handy, so this is just a matter of applying the desired style.

@terpimost do you have a design for this already in Figma? I see the streams screen at https://www.figma.com/file/1JTNtYo9memgW7vV6d0ygq/Zulip-Mobile?node-id=112%3A9610&mode=dev , but it doesn't look like any of those are shown as muted.

**Comment by terpimost** [comment]
I don't have the design yet. but I suggest to make them 50-60% transparency:
<img width="414" alt="image" src="https://github.com/zulip/zulip-flutter/assets/1903309/dbb8e35e-0be5-4d55-9b2d-4d9a565940a6">
But we do want the background to be white, otherwise it would break the list

**Comment by dhruvpatidar359** [comment]
may i work on this issue , if the design is decided  ?

**Comment by gnprice** [comment]
Yeah, the draft design above is enough that we can go ahead and implement this. We can always adjust the design later.

@dhruvpatidar359 do take a look though at our README section on picking an issue to work on: https://github.com/zulip/zulip-flutter#picking-an-issue-to-work-on
