### ISSUE TITLE
AboutZulipPage: "Licenses" page broken

### ISSUE THREAD

**Issue by chrisbobbe** [zulip/zulip-flutter#435]
![D16E5638-1896-4FB7-9D68-A5098408F5D3](https://github.com/zulip/zulip-flutter/assets/22248748/9d5dc6c5-dff3-48fd-8a2e-c040c04e043d)

**Comment by gnprice** [comment]
Oops, good catch. Guess we need to take care of removing from this list when we remove a third-party asset, as well as adding when we add one.

(Though in this case we actually want to add the asset back again anyway, as I see you have a PR to do.)
