### ISSUE TITLE
Default Theme of Choose Account Page/Add an account page not same as system theme.

### ISSUE THREAD

**Issue by Shikhar12233456** [zulip/zulip-flutter#452]
![WhatsApp Image 2023-12-14 at 16 20 05](https://github.com/zulip/zulip-flutter/assets/88368793/8722b6b1-845d-4125-9553-1e9b19d2890c)
![WhatsApp Image 2023-12-14 at 16 20 04](https://github.com/zulip/zulip-flutter/assets/88368793/fdc4563d-c897-4392-8691-b0295e385b4e)

My default system theme is Dark.

**Comment by sirpengi** [comment]
Hiyah! Thanks for the report, we haven't yet implemented support for dark theme but we've already got an issue open to track progress on it. See #95 . Closing this as a duplicate!

**Comment by Shikhar12233456** [comment]
Hey @sirpengi, If you have a Figma file or design related to the theme. Please share with me, I want to contribute to this project.
