### ISSUE TITLE
Pass new `read_by_sender` flag when sending messages

### ISSUE THREAD

**Issue by timabbott** [zulip/zulip-flutter#473]
See https://zulip.com/api/send-message#parameter-read_by_sender and https://chat.zulip.org/#narrow/stream/378-api-design/topic/read_by_sender.20flag.20on.20send-message/near/1702407 for details.

**Comment by gnprice** [comment]
This was actually already done in #456 (as the fix for #440). I see we didn't mention that in the `#api design` thread — mentioning it there would have been good.
