### ISSUE TITLE
Increase content font size

### ISSUE THREAD

**Issue by gnprice** [zulip/zulip-flutter#512]
This is a sub-issue of:
* #157

Currently the app's font size for plain text in message bodies is 14px. That dates from the early prototype phase, when I was copying web's design meticulously (to demonstrate that we could).

The corresponding size in the zulip-mobile legacy RN app is 16px, I believe.

The corresponding size in @terpimost's design in Figma is 17px. For example, see [here](https://www.figma.com/file/1JTNtYo9memgW7vV6d0ygq/Zulip-Mobile?type=design&node-id=538-20849&mode=design&t=8UJkvvqjxtix3FQO-0).

So we should increase the size, either to 16px or 17px.

If we're unsure which of those sizes to prefer, we could add a setting (even if only for the beta period) — that would make it easy for beta users to experiment with the different values and take crisp apples-to-apples pairs of screenshots for discussion.

Chat thread: https://chat.zulip.org/#narrow/stream/48-mobile/topic/density.20in.20message.20list/near/1733351

**Comment by vijay-kesanakurthi** [comment]
I want to work on this, to get a better understanding of the project for GSOC.

**Comment by gnprice** [comment]
@vijay-kesanakurthi Ah, we should have marked this sooner — this is actually an issue that a member of the core team is planning to take care of within the next week. I'll mark it as assigned now.

There are plenty of other issues [on our project board](https://github.com/orgs/zulip/projects/5/views/4), though, that don't have anyone assigned, so I'd encourage browsing through those. And if you haven't already, please take a look at the Zulip project's guide for picking an issue to work on: https://zulip.readthedocs.io/en/latest/contributing/contributing.html#picking-an-issue-to-work-on
