### ISSUE TITLE
Bug: Email Authentication Failure Due to Trailing Space in Input

### ISSUE THREAD

**Issue by Mehul-Kumar-27** [zulip/zulip-flutter#518]
When a user enters their email and password in the login text fields, and unintentionally adds a space at the end of the email, the space is erroneously included in the email input. Consequently, this leads to an email mismatch during authentication, resulting in login failures.

**Expected Behavior**
The system should recognize and trim any trailing spaces in the email input to ensure accurate authentication.

https://github.com/zulip/zulip-flutter/assets/97253470/28cc536d-2da7-418a-8d3a-161c7c2fd9a6

**Comment by gnprice** [comment]
Thanks for the report! I agree this would be good to fix.

**Comment by Narasimha677** [comment]
hi @gnprice can I Solve this Issue?

**Comment by gnprice** [comment]
@Narasimha677 The issue is already assigned to @Mehul-Kumar-27, and he has a PR for it that's near completion. So I don't think this is a useful one for another contributor to try to pick up.

**Comment by Narasimha677** [comment]
@gnprice Thanks for the Response
