### ISSUE TITLE
content: Inline code uses paragraph font size, even in headings (h1, etc.)

### ISSUE THREAD

**Issue by chrisbobbe** [zulip/zulip-flutter#538]
![image](https://github.com/zulip/zulip-flutter/assets/22248748/379e852c-4972-44e5-98d1-d5e4c6b555e7)

**Comment by chrisbobbe** [comment]
Oh, this is also true of user mentions and timezone-aware times:

![image](https://github.com/zulip/zulip-flutter/assets/22248748/3b81339b-4075-4868-8f04-c00d6b52da12)

(Also, for those elements, they aren't getting bolded as they should.)

**Comment by gnprice** [comment]
Oops, #541 had a classic GitHub accidental-close phrase :slightly_smiling_face:: "doesn't fix #538."

**Comment by chrisbobbe** [comment]
Agh! Thanks for the catch!
