### ISSUE TITLE
Set letter spacing to 1% in buttons

### ISSUE THREAD

**Issue by gnprice** [zulip/zulip-flutter#548]
This is a followup to #545. That issue is focused on the one most conspicuous kind of text in the app; this one is for the rest of the app.

Specifically we want:
* letter spacing of 1% (i.e., 0.01 times `fontSize`) in buttons;
* ~~`letterSpacing: 0` everywhere else, except where the Figma design specifies otherwise.~~ (This part was handled in #549.)

[Chat thread](https://chat.zulip.org/#narrow/stream/48-mobile/topic/letter.20spacing/near/1751385).

**Comment by Gosplex** [comment]
Hello @gnprice 
I am interested in working on this issue
Please could i get started?

**Comment by gnprice** [comment]
Hi @Gosplex, welcome.

I think we're not going to want to do this by setting `letterSpacing` individually on each of the buttons in the app, or on each of the other pieces of text. That would make it error-prone because it'd be easy to forget to include it in a given place when adding a new piece of UI, and it'd also make for additional noise when reading the code for each place text appears.

Instead, we'll use the "theme" features of Flutter's Material Design implementation. See `TextTheme` and related docs:
https://main-api.flutter.dev/flutter/material/TextTheme-class.html
https://main-api.flutter.dev/flutter/material/Typography-class.html

Your first step will be to find the existing code in the app that works with those APIs, and start to get an idea of how you'd approach addressing this issue there.

There's also several button-related "theme" classes, which control the text (and other things) in buttons specifically. So you'll want to find those and get an idea of how you'd address the buttons part of this issue using those.

**Comment by Gosplex** [comment]
After reviewing the resources on Flutter's theming, I suggest centralizing `textTheme` and `buttonTheme` declarations using `ThemeData` in a dedicated file. This ensures consistent letter-spacing and style throughout the app, improving maintainability. I'm open to suggestions for further refinement.

**Comment by Gosplex** [comment]
Good day
So I have carefully gone through the codebase  and the help material provided by @gnprice  and I found out that the `ThemeData` of the app is managed at `app.dart` file. So any changes made there would be made available throughout the app

**Comment by gnprice** [comment]
Cool, please go ahead. Note that part of this issue is now done, so the remaining part is the part about 1% letter spacing in buttons.

For an example of how we adjust themes systematically, take a look at #549 and the file that PR modified. We'll need to do something similar for the button themes.

**Comment by Gosplex** [comment]
@gnprice  Sir
I have created a pull request for this issue.
Please review. 
Thanks a bunch
