### ISSUE TITLE
Bug: system keyboard hides immediately during password input

### ISSUE THREAD

**Issue by foxyseta** [zulip/zulip-flutter#552]
When tapping on the password field, my Android system keyboard shows on screen and then hides again immediately. I need to be extremely fast in typing the first character of my password before the keyboard hides again and then repeat the process once for every character of my password. This does not happen with any other app installed on my system. Maybe the keyboard hides because there is not enough space for it and the input fields on the screen?

LineageOS 20, Android 13, August 9, 2023
Android Keyboard (AOSP) version 13, com.android.inputmethod.latin
Zulip Beta version 0.0.11, com.zulip.flutter

**Comment by chrisbobbe** [comment]
A video recording would be very helpful for us to understand the details; are you able to provide one?

**Comment by foxyseta** [comment]
https://github.com/zulip/zulip-flutter/assets/12249077/8c01fee9-59b1-4daf-be77-296235b26c1f

Sure! Is this okay?

**Comment by gnprice** [comment]
Interesting, thanks for the report! That looks like an awfully frustrating symptom.

I tried some searches in the upstream Flutter tracker, and didn't find any definite matches. The one possible match I found was:
* https://github.com/flutter/flutter/issues/94249

and there's a somewhat similar (but distinct) symptom at:
* https://github.com/flutter/flutter/issues/23896

So it seems like some more debugging will be required.

AFAIK there's nobody on the core team who has a LineageOS device. So it may not be easy for us to reproduce the issue if it only appears there.

It sounds like you've been able to win the race and enter your password to log in. If so, I'm curious if you find similar behavior anywhere else in the app — that could help narrow down what's involved.

**Comment by foxyseta** [comment]
Hadn't thought about checking upstream. Nice catch!

Actually, after successfully inputting the first character, the bug seems to stop. In other words, it only presents itself with the empty input fields. Will definitely let you know if something like this happens in other screens of the app.

**Comment by gnprice** [comment]
Cool, thanks for the update. And do keep us posted.

**Comment by chintu4** [comment]
Is this error got resolved?

**Comment by foxyseta** [comment]
It now works on 0.0.13. As I encountered this error in 0.0.11, not sure if it was fixed in 0.0.12 or 0.0.13.

Thanks!
