### ISSUE TITLE
Add images from compose box

### ISSUE THREAD

**Issue by gnprice** [zulip/zulip-flutter#56]
I.e., the feature represented by a "picture" icon under the compose box, in the existing RN app.

This should present the user with an appropriate image-picker UI from the platform, where they're able to select from the images they have on the device.

After the user selects an image, they should have the opportunity to add text before sending the message. (We only fixed that pretty recently in the RN app: https://github.com/zulip/zulip-mobile/issues/4540 . But it was a bad UX before that, which we shouldn't repeat.) Probably this means doing the same thing we do now (since https://github.com/zulip/zulip-mobile/pull/5474) in the RN app, which is also what we do in the web app: we immediately insert a placeholder into the message text, then start the upload, and when the image is uploaded and we have a URL for it we fill in the placeholder.

For implementing the platform side of this feature:
- Flutter has a first-party plugin [`image_picker`](https://pub.dev/packages/image_picker).
    - 80 open issues, of 390 total; see [ranked by upvotes](https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+image_picker%22+sort%3Areactions-%2B1-desc).
    - Bulk of the top issues are closed. Looking at the top remaining issues, none seem worrying.

**Comment by chrisbobbe** [comment]
Sure, good to use a first-party plugin. If we run into a problem with `image_picker`, I think [`file_picker`](https://pub.dev/documentation/file_picker/latest/) (used in #57, attaching generic files) also offers the option to open this kind of image-specific UI, if you ask it to by passing a param ([`type`](https://pub.dev/documentation/file_picker/latest/file_picker/FilePicker/pickFiles.html)).

**Comment by chrisbobbe** [comment]
Ah, I may have already run into a problem: `image_picker` lets you call [a method to pick an image](https://pub.dev/documentation/image_picker/latest/image_picker/ImagePicker/pickImage.html) OR [a method to pick multiple images](https://pub.dev/documentation/image_picker/latest/image_picker/ImagePicker/pickMultiImage.html) OR [a method to pick a video](https://pub.dev/documentation/image_picker/latest/image_picker/ImagePicker/pickVideo.html). We want a method that lets you pick from a mixed list of images and videos, and that lets you pick one or more.

`file_picker` seems to do that job nicely; let's try using that.

**Comment by gnprice** [comment]
> We want a method that lets you pick from a mixed list of images and videos, and that lets you pick one or more.

Yeah. Looks like that's https://github.com/flutter/flutter/issues/89159 and https://github.com/flutter/flutter/issues/102283 .

Sure, we can try `file_picker`. I'm curious what kind of UI it presents in that case — whether it's a proper "image gallery" style of UI that's focused on the contents of the images, or still a "file browser" style of UI.

**Comment by chrisbobbe** [comment]
> Sure, we can try `file_picker`. I'm curious what kind of UI it presents in that case — whether it's a proper "image gallery" style of UI that's focused on the contents of the images, or still a "file browser" style of UI.

On iOS, it looks like what we want:

![IMG_2324](https://user-images.githubusercontent.com/22248748/232936353-dec61e05-a251-487a-8acc-fa9a5bb13828.png)

Will test on Android next. 🙂

**Comment by chrisbobbe** [comment]
Hmm, this doesn't look like what we'd want on Android (office device):

<img width=400 src="https://user-images.githubusercontent.com/22248748/232939040-4b5721cc-187a-4b12-88fa-7c42911072b1.jpg">

But before giving up on `file_picker` for Android, I'd like to try on Android 13 or later; the office device is running Android 9. It's possible this library uses later Android's `PhotoPicker` API which led to an improvement in the RN app zulip/zulip-mobile@e4d162cc1d69216b1aa52056d9244cbf5a54930a.

**Comment by chrisbobbe** [comment]
Hmm no, I don't think this is the fancy new `PhotoPicker` API:

<img width="402" alt="image" src="https://user-images.githubusercontent.com/22248748/232940643-3ef1c2fd-31e8-42e9-9024-c23ae4db03c9.png">

And if I search for "PhotoPicker" in the `file_picker` GitHub repo I get no results: https://github.com/search?q=repo%3Amiguelpruivo%2Fflutter_file_picker%20PhotoPicker&type=code

So yeah, maybe we'll want to do something different for Android. Hmm.
