### ISSUE TITLE
notif: Translate "to you and N others", handling number properly

### ISSUE THREAD

**Issue by gnprice** [zulip/zulip-flutter#573]
See [chat thread](https://chat.zulip.org/#narrow/stream/48-mobile/topic/notifications.20differences/near/1757473).

The report is only about fixing the singular/plural handling in English: we currently show "and 1 others". But to fix it, we should just internationalize this string, and then the number handling will get fixed automatically as part of that.

There's an existing TODO comment in the code for this:
```dart
        '${data.senderFullName} to you and ${allRecipientIds.length - 2} others', // TODO(i18n), also plural; […]
```

**Comment by abelaba** [comment]
@gnprice. I can get started on this.
