### ISSUE TITLE
Limited Emoji Reactions Available in Zulip Mobile App

### ISSUE THREAD

**Issue by Syrineladeb02** [zulip/zulip-flutter#601]
When using the Zulip mobile app, I've observed that there's a limited selection of emoji reactions available when reacting to a message. Currently, only the "OK" emoji with a finger is available for reactions. Having a broader selection of emoji reactions would greatly enhance communication within the app and allow users to express a wider range of emotions.

Steps to Reproduce:

1/Open the Zulip mobile app.
2/Navigate to a message that allows reactions.
3/Attempt to react to the message and observe the available emoji options

![screen1](https://github.com/zulip/zulip-flutter/assets/152219936/0e2cadcb-f10e-4320-87ef-a6057720283c)

**Comment by chrisbobbe** [comment]
Hi @Syrineladeb02, thanks for the report, especially the effort in creating the screenshot and reproduction recipe.

This feature is already tracked in #388, so I'll close this as a duplicate.
