### ISSUE TITLE
Open camera to take and share a photo

### ISSUE THREAD

**Issue by gnprice** [zulip/zulip-flutter#61]
This is the feature indicated by a "camera" icon below the compose box in the zulip-mobile RN app. It's a standard, expected feature for a messaging application on a mobile device.

Flutter has a first-party plugin for this: https://pub.dev/packages/camera and that's probably what we want to use.
* Flutter Cookbook recipe: https://docs.flutter.dev/cookbook/plugins/picture-using-camera
* See [193 open issues](https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+camera%22), 458 total.
  * No stale-bot — this is the Flutter tracker — so that's an honest open-issues count.

---

Further notes on the `camera` plugin:

The plugin's Android implementation is [being rewritten](https://github.com/flutter/flutter/issues/107260) to use Android's new [CameraX](https://developer.android.com/training/camerax) API.
* Design doc gives some background:
  > There are a large number of device-specific issues with the current Android camera implementation (about 30% of all filed camera issues). These issues are extremely difficult for us to tackle since they may require access to specific devices, involve hardware issues, or require undocumented or hacky workarounds.

  Android upstream has invested in solving that problem (see the photo of an automated physical-phone-with-camera test lab in [the CameraX doc](https://developer.android.com/training/camerax)), and CameraX is the result.
* Tracked as [a GitHub project board](https://github.com/flutter/flutter/projects/230); see [as issue search](https://github.com/flutter/flutter/issues?q=project%3Aflutter%2Fflutter%2F230).
  - It looks like work on implementing this project started around the beginning of 2023. Perhaps it'll be finished later in 2023?
* So at present the plugin is less reliable on Android than one would like. But probably our best path to solve that is to just go ahead and use the first-party plugin, and wait for it to improve with the switch to CameraX.

Meanwhile on the iOS side:
* Filtering to iOS issues: 28 open, of 66 total. See [ranked by upvotes](https://github.com/flutter/flutter/issues?q=is%3Aissue+label%3A%22p%3A+camera%22+label%3Aplatform-ios+sort%3Areactions-%2B1-desc).
  - All have far fewer upvotes than the top-voted Android issues, indicating there aren’t a lot of developers running into them.
  - The top few issues don’t look too concerning: specific to uncommon use cases like taking video, or happen infrequently.
  - Some of the top issues that do look relevant: [#25959](https://github.com/flutter/flutter/issues/25959) latency; [#89216](https://github.com/flutter/flutter/issues/89216) a messy issue about camera orientation.

**Comment by chrisbobbe** [comment]
For this feature, a convenient API will let us take the user to a native camera UI, then take them back to the app with a picture or video so we can upload it.

I'm not finding an API like that in the `camera` library. I do see that it gives access to the camera, but in a different way: from within the app, you can call things like [`takePicture`](https://pub.dev/documentation/camera/latest/camera/CameraController/takePicture.html), [`startVideoRecording`](https://pub.dev/documentation/camera/latest/camera/CameraController/startVideoRecording.html), and [`stopVideoRecording`](https://pub.dev/documentation/camera/latest/camera/CameraController/stopVideoRecording.html), and you can show a live preview of what the camera sees, with the [`CameraPreview`](https://pub.dev/documentation/camera/latest/camera/CameraPreview-class.html) widget. It seems like in theory we could use this to build a custom photo/video-capturing UI ourselves, but I think we should just take user to a camera UI from the platform.

At a glance, it looks like Flutter's first-party plugin [`image_picker`](https://pub.dev/documentation/image_picker/latest/) looks like it has what we'd want for that.

**Comment by chrisbobbe** [comment]
Hmm, ideally we'd open a platform interface that lets you choose between taking a photo and a video. `image_picker` doesn't yet have that option: flutter/flutter#89159

Would it be clunky to have two buttons for camera capture: one for photos, and one for videos?

Also, `zulip-mobile` doesn't offer uploading from captured video either, so I guess one option pending flutter/flutter#89159 is to leave video-capturing as a TODO.

**Comment by gnprice** [comment]
> It seems like in theory we could use this to build a custom photo/video-capturing UI ourselves,

Hmm, I see. Yeah, that's not the kind of API we want here. I guess `image_picker` is the upstream solution for the interaction we do want.

I think it's fine to not support taking a video.
