### ISSUE TITLE
Try faster fade-out on mark-as-read button

### ISSUE THREAD

**Issue by gnprice** [zulip/zulip-flutter#613]
This is a followup to:
* #562 
* #565

See [chat thread](https://chat.zulip.org/#narrow/stream/243-mobile-team/topic/messages.20shift.20on.20mark-as-read/near/1773710).

**Comment by alya** [comment]
I've been noticing this one when I use the app.

**Comment by gnprice** [comment]
Specifically, per [Vlad's suggestion](https://chat.zulip.org/#narrow/stream/48-mobile/topic/messages.20shift.20on.20mark-as-read/near/1800824) yesterday:
* Let's have it fade out in 100ms, rather than 2000ms.
* Let's also try having the animation scale the button down, as well as reducing opacity.

In the future it would be good to have the button respond optimistically, without waiting for an ack from the server. (I'll file an issue for that.) Then we can make the animation longer again, because there won't be the built-in delay from waiting for the server.
