### ISSUE TITLE
Remove "under construction" from home page

### ISSUE THREAD

**Issue by gnprice** [zulip/zulip-flutter#614]
The app's home screen has the text:
> 🚧 Under construction 🚧

That was accurate when I wrote it, when the app was a prototype less than an hour old (c4ede10fdb729ddc5e22845252afb3539085fe01, 00c09d597c60d1f9b14f71bf41f5eb8e7ec5334b). But it doesn't fit so well now.

We should cut that and some of the other data on that screen that isn't relevant for the user.

Mentioned in chat here:
https://chat.zulip.org/#narrow/stream/48-mobile/topic/Flutter.20app.20.2B.20SAML.20auth/near/1774010

**Comment by mohitsatr** [comment]
![Screenshot_20240817_094034](https://github.com/user-attachments/assets/e1f1d732-5979-4448-8692-103eb926229f)
@gnprice i think "Under Construction" is the only unnecessary thing that needs to be removed.

**Comment by PIG208** [comment]
Other than "Under construction", we should also be able to remove "Subscribed to..." (this line predates the subscription list page.

We can also remove "connected to" because we basically have that from the account selection page.

Not sure about the server version, as that's not available elsewhere in the UI yet, but it wouldn't hurt to remove it too.

**Comment by gnprice** [comment]
Yeah, all of those lines are basically superfluous.

I think the realm URL (the thing after "Connected to:") is actually useful to keep for the moment — it helps you confirm which account you're looking at. Especially helpful if you didn't get here from the choose-account page: for example you simply started up the app (and were already logged in).

**Comment by prakhar1144** [comment]
I'm planning to contribute to the flutter project in my free time, and this issue looks like a simple enough issue to start with.

I think @mohitsatr hasn't started working on it yet, so I'll open a PR by Saturday. (@mohitsatr , feel free to drop a comment if you already have made changes locally to fix this -- I'll look for another issue. Thanks!)

**Comment by mohitsatr** [comment]
@prakhar1144 go ahead

**Comment by ArpanMondalGITHUB** [comment]
i think @prakhar1144  hasn't started working on it yet , so can i open a PR . i started to made changes locally to fix this . @prakhar1144  if u also change the code in locally then no worry i can review the code or will look for another issue.
