### ISSUE TITLE
Star icon too high on messages

### ISSUE THREAD

**Issue by gnprice** [zulip/zulip-flutter#616]
In the message list, when a message is starred, the star icon appears too high relative to the message text:
![image](https://github.com/zulip/zulip-flutter/assets/28173/2fb93022-abe6-4783-bb7c-29d2f8a938fd)

See [chat thread](https://chat.zulip.org/#narrow/stream/48-mobile/topic/star.20location/near/1769933) for discussion.

Instead, the "shoulders" of the star (the near-horizontal top edges of the left and right wedges of the star) should be at about the x-height of the first line of text, i.e. about the same height as the top of letters like "x" and "e". Like this (from [this PR subthread](https://github.com/zulip/zulip-flutter/pull/449#discussion_r1452645175)):
![image](https://github.com/zulip/zulip-flutter/assets/28173/b8637837-5263-4848-a81d-d580c40ab0f2)

**Comment by PIG208** [comment]
A side by side comparison when the system font size changes using the configuration from #616 where the top inset of the star is set to 5.5 (originally 4):

![image](https://github.com/zulip/zulip-flutter/assets/39874143/89fdb78f-f0f6-45cb-9186-35907b64c662)

Ideally we want to make sure the alignment is responsive regardless of the font size. So using a constant is likely not an ideally solution.
