### ISSUE TITLE
Experiment with CupertinoContextMenu

### ISSUE THREAD

**Issue by gnprice** [zulip/zulip-flutter#62]
In iOS there's a UI element called a ["context menu"](https://developer.apple.com/design/human-interface-guidelines/components/menus-and-actions/context-menus), which one gets when long-pressing something, and provides access to things you can do with the thing pressed.

It'd be neat to use something like this in place of our action sheets, at least on iOS.

Previously we've [discussed](https://chat.zulip.org/#narrow/stream/243-mobile-team/topic/context.20menu.20possibility/near/1421575) trying to do something in this direction in the zulip-mobile React Native app. The options for doing so on RN are not great, especially if one wants to do it on Android as well as iOS. Instead, what we currently do in the RN app is that on iOS we have a native [action sheet](https://developer.apple.com/design/human-interface-guidelines/components/presentation/action-sheets), and on Android we have a less-slick custom action sheet provided by a third-party library.

Flutter has a [`CupertinoContextMenu` widget](https://api.flutter.dev/flutter/cupertino/CupertinoContextMenu-class.html) which aims to provide this feature, so we could use that. More about that widget:
* [Top issues (searching for "cupertinocontextmenu")](https://github.com/flutter/flutter/issues?q=is%3Aopen+label%3A%22f%3A+cupertino%22+cupertinocontextmenu+sort%3Areactions-%2B1-desc)
* The two with actual significant numbers of upvotes (42560 and 60298) are requests for unrelated features, where the thread just happens to mention this one.
* Some fidelity issues. Ongoing work fixing them; e.g. it got a lot better in 2023-02 thanks to https://github.com/flutter/flutter/pull/117698.

**Comment by gnprice** [comment]
Like Flutter's "Cupertino" widgets in general, this CupertinoContextMenu widget should function just as well on Android (or other platforms) as it does on iOS, so we'd have the option to use it everywhere.

I suspect that it'd feel out of place for Android users, and that on Android we'll want to stick with a [bottom sheet](https://m3.material.io/components/bottom-sheets/guidelines), which is what zulip-flutter currently uses on all platforms. But that's a design choice we can make once we see it in action.

This issue is for experimenting with CupertinoContextMenu primarily on iOS.

**Comment by terpimost** [comment]
For me context menu in Android world is https://m3.material.io/components/menus/overview

If we are going to use bottom sheet I would rather work on that and polish such implementation than polishing both approaches.

Here is the example how we could convert iOS menu to bottom sheet.
![image](https://user-images.githubusercontent.com/1903309/233104471-c8045545-ba80-4e6f-b610-04b787d62737.png)
![image](https://user-images.githubusercontent.com/1903309/233104542-9e57fb37-ee6b-4ae6-9be3-a30e42f0b0bf.png)


Later we could figure out if a small interactive tooltip could be used to improve UX for emoji or something like this:
<img width="772" alt="image" src="https://user-images.githubusercontent.com/1903309/233105054-3e2b605d-4df1-4f62-9d72-bf716b8dc2c3.png">

**Comment by gnprice** [comment]
> For me context menu in Android world is https://m3.material.io/components/menus/overview

Yeah. I agree with that terminology, but it feels to me like quite a different kind of UI from the Apple "context menu".

In particular the Apple "context menu" would be an appropriate fit for the UI to present when the user long-presses a message, with a design just like in your first screenshot above. But I think the Material "menu" would not be a good fit for that, whereas the [Material "bottom sheet"](https://m3.material.io/components/bottom-sheets/overview) (which is what we currently have in the zulip-flutter prototype, and is basically the same concept as the "action sheet" we have in the zulip-mobile RN app) is a good fit there.

> If we are going to use bottom sheet I would rather work on that and polish such implementation than polishing both approaches.

Sure, sounds good.

In that case, perhaps let's close this issue, and open a new one for adjusting the design of the bottom sheet to correspond to your second screenshot above.

**Comment by gnprice** [comment]
Filed #90 for that design change.
