### ISSUE TITLE
Web auth sometimes fails

### ISSUE THREAD

**Issue by gnprice** [zulip/zulip-flutter#620]
See detailed report [in chat](https://chat.zulip.org/#narrow/stream/48-mobile/topic/Flutter.20app.20.2B.20SAML.20auth/near/1775625).

Some potentially key details include:
* This was on Android.
* The browser which powered the webview was Firefox for Android.
* After redirecting to the app:
  > When I am sent back to the app, it just shows the main "Choose account"//"Add an account" page. There is no error message

**Comment by chrisbobbe** [comment]
Responded in the linked chat thread with some thoughts, including a potential solution that I want to check with Greg when he's back from vacation.
