### ISSUE TITLE
Where can we download the beta Android app to test?

### ISSUE THREAD

**Issue by carun** [zulip/zulip-flutter#658]

**Comment by chrisbobbe** [comment]
This is answered in the project README: https://github.com/zulip/zulip-flutter?tab=readme-ov-file#using-zulip

If you have more questions, please ask in the [Zulip development community](https://zulip.com/development-community/). This is the issue tracker for bugs and features.

**Comment by carun** [comment]
Great, thanks @chrisbobbe! The beta app is looking awesome, far better than the current official mobile app. I'll ping on the chat stream to confirm a few issues.
