### ISSUE TITLE
Experiment with small caps as a font feature

### ISSUE THREAD

**Issue by gnprice** [zulip/zulip-flutter#66]
In some places in the web UI, we've started to use small caps. It would be good to demonstrate doing so in Flutter.

Flutter has extensive support for font variations. See [`FontFeature`](https://api.flutter.dev/flutter/dart-ui/FontFeature-class.html), and more generally [`TextStyle`](https://api.flutter.dev/flutter/painting/TextStyle-class.html). So it should be straightforward to demonstrate this, given a font that has small caps in the first place.

In particular Source Sans fonts have [several features including](https://beautifulwebtype.com/source-sans-pro/) small caps (`smcp`) and slashed zero (`zero`). So we can do this once we're bundling such a font: #64.

Other related issue:
* A different axis of fancy font features: #65

**Comment by terpimost** [comment]
The place where we about to use small caps is dates: 
![image](https://user-images.githubusercontent.com/1903309/233103282-030667df-7e6a-44f1-a678-07991d9a2e4b.png)

Not critical but very nice to have

**Comment by gnprice** [comment]
This is now effectively part of #157.
