### ISSUE TITLE
Set "typing" status

### ISSUE THREAD

**Issue by gnprice** [zulip/zulip-flutter#666]
I.e., half of this feature:
https://zulip.com/help/typing-notifications
along with #665.

In the API, the relevant endpoint is:
https://zulip.com/api/set-typing-status

For an implementation for comparison, see zulip-mobile's `sendTypingStart` and `sendTypingStop`, or the corresponding code in Zulip web.

**Comment by IfeanyiSam** [comment]
Is this issue open to be worked on?

**Comment by chrisbobbe** [comment]
No, #897 is already in progress for this issue. Please choose a different one.
