### ISSUE TITLE
msglist/dm: Provide proper feedback when sending DMs to a deactivated user

### ISSUE THREAD

**Issue by sm-sayedi** [zulip/zulip-flutter#675]
When trying to send a DM message to a deactivated user, the message goes into void and nothing happens so the user knows they're exchanging messages with a deactivated user.

Here's how it looks right now:

<img src="https://github.com/zulip/zulip-flutter/assets/59946442/eb99074c-b1c4-4c1c-883c-282adf8a3011" width="300" />
<br/>
<br/>
This is how the web handles it:
<img src="https://github.com/zulip/zulip-flutter/assets/59946442/f939dcb9-4921-4598-b3ed-746993db744f" />
<br />
<br />
The react-native mobile app just shows an infinite loading indicator on the right side of the message.

**Comment by gnprice** [comment]
Thanks! Agreed, we should fix this.
