### ISSUE TITLE
content/msglist: Horizontal scrollbar in code block sometimes has wrong vertical position

### ISSUE THREAD

**Issue by chrisbobbe** [zulip/zulip-flutter#736]
In the code block in this screenshot, the scroll bar should be positioned lower than it is:

<img width=400 src="https://github.com/zulip/zulip-flutter/assets/22248748/7af836e0-11aa-4566-a903-0c38adc86093">

I think it might have to do with the bottom inset. I seem to be seeing it in the "Combined feed" but not any other message-list views. "Combined feed" behaves differently about padding the bottom inset because it doesn't show the compose box.

**Comment by chrisbobbe** [comment]
Looks like this broke in this commit:

6a8cf5cf3 msglist [nfc]: Unpack to a CustomScrollView of a single sliver

From `CustomScrollView`'s dartdoc:

```dart
/// [CustomScrollView]s don't automatically avoid obstructions from [MediaQuery]
/// like [ListView]s do. To reproduce the behavior, wrap the slivers in
/// [SliverSafeArea]s.
````

Here's before and after that commit (which was in January, so the appearance won't be current in either screenshot):

| Before | After |
| --- | --- |
| ![C6CEB09A-7695-4087-87AA-D1089732AC8A](https://github.com/zulip/zulip-flutter/assets/22248748/d7f9e8ee-5cce-414e-94e8-3cfffe325c36) | ![2D3A22ED-DA45-4920-9E2D-0BCDDB59DAF5](https://github.com/zulip/zulip-flutter/assets/22248748/1b760fa3-4fbd-4801-8a51-d6799fd16053) |

**Comment by chrisbobbe** [comment]
We could fix it in `main` by wrapping our `SliverStickyHeaderList` sliver in a `SliverSafeArea`, when the narrow is "Combined feed". (And add a `TODO(#311)` like the ones we have already.)

@gnprice, would this approach disrupt your work toward #82?

Then for a regression test, maybe we render a `CodeBlock` in the message list on the "Combined feed" page, and check that it receives a `MediaQuery.padding.bottom` of zero.

**Comment by gnprice** [comment]
Hmm interesting, good catch.

Wrapping in a `SliverSafeArea` would mean that the actual list stays out of the bottom inset area, right? That doesn't seem like the desired behavior — I think it's expected that the messages scroll visibly through that bottom area.

A `MediaQuery.removePadding` might be a good fix. That would mean that the list forgets that there is a bottom inset.

**Comment by chrisbobbe** [comment]
> Wrapping in a `SliverSafeArea` would mean that the actual list stays out of the bottom inset area, right? That doesn't seem like the desired behavior — I think it's expected that the messages scroll visibly through that bottom area.

Hmm, this isn't what I'm seeing: screenshots at PR #738.
