### ISSUE TITLE
login: Gboard clipboard doesn't obscure password

### ISSUE THREAD

**Issue by rajveermalviya** [zulip/zulip-flutter#743]
| zulip-flutter | zulip-mobile |
| - | - |
| <img width="426" alt="Screenshot 2024-06-18 at 19 57 40" src="https://github.com/zulip/zulip-flutter/assets/36819268/5b60ef67-4589-4a5a-afb5-e662441bed35"> | <img width="426" alt="Screenshot 2024-06-18 at 20 12 55" src="https://github.com/zulip/zulip-flutter/assets/36819268/f2b663fa-02df-4f73-b116-35af61cd08fa"> |

**Comment by gnprice** [comment]
Hmm, good find!

This would definitely be worth spending a bit of time looking for an upstream Flutter issue about. Or if there isn't one, then making a small repro and reporting the issue.
