### ISSUE TITLE
Experiment with navigation stack (esp. Android)

### ISSUE THREAD

**Issue by gnprice** [zulip/zulip-flutter#75]
@terpimost writes:
> Flutter is a single activity so we don’t get navigation history for free. We should check how good we can control where Android back button leads to.

Flutter offers an API for controlling navigation, with a variety of features. The entry point to the relevant docs is here:
https://docs.flutter.dev/development/ui/navigation

So we should experiment with that and satisfy ourselves that we'll be happy with it.

**Comment by gnprice** [comment]
The zulip-flutter prototype has always used a navigation stack, mostly in the most basic way: push a new route, or pop the current route.

With the login flow #11, we introduced a more complex bit of navigation for the first time:
* From the starting screen (the choose-account page), if you hit the "Add an account" button, then enter a URL on the next screen, then get to the email-and-password screen, that's all basic stack navigation. If you go back from the URL screen you get the choose-account screen, and back from the email-and-password screen you get the URL screen, like normal.
* But then if on the email-and-password screen you successfully log in, you get the per-account home screen for that account — and if you go back from *there*, you go straight back to the choose-account page. The screens representing the login flow itself are gone. I figured that's the appropriate way for that interaction to go.

What's happened is that upon successfully logging in, at the same time as pushing the new account's home screen onto the nav stack, I've popped from the stack the screens that represented the login flow. That code uses [`NavigatorState.pushAndRemoveUntil`](https://api.flutter.dev/flutter/widgets/NavigatorState/pushAndRemoveUntil.html), and it looks like this:
https://github.com/zulip/zulip-flutter/blob/915216760c78f6624f9cd46568dad525fc9664ab/lib/widgets/login.dart#L157-L160

So that's certainly an example of controlling the navigation history.

@terpimost Are there further navigation-history experiments that you'd particularly like to see?

**Comment by terpimost** [comment]
I guess a very simple one could be sliding out the navigation list: and sliding it back down with a back button:
<img width="557" alt="image" src="https://user-images.githubusercontent.com/1903309/233847772-859a2c04-a9ed-4a4f-82bb-8cb1cf0989cb.png">

Another one could be opening compose editor and going back out of it by clicking Back button.

And a classic is tabs... so if I switch between tabs what would back button do? I switch from streams to DMs, to mentions. At this point what would back button do? Does it close the app? My suggestion is that the very top item in history stack it is some default home screen or inbox.

**Comment by gnprice** [comment]
Cool, thanks.

> Another one could be opening compose editor and going back out of it by clicking Back button.

Just tested, and it looks like this is already our behavior.

(Well, I used the system gesture for "back", because gesture navigation is the default [since Android 10](https://android-developers.googleblog.com/2019/08/gesture-navigation-backstory.html). But should be the same with a back button.)



> I guess a very simple one could be sliding out the navigation list: and sliding it back down with a back button:

> And a classic is tabs... so if I switch between tabs what would back button do? […] Does it close the app? My suggestion is that the very top item in history stack it is some default home screen or inbox.

I agree. These will be things to experiment with when we add a navigation list and/or tabs, then.

**Comment by gnprice** [comment]
Closing this because the actual experimenting is complete. When we add a navigation list and/or tabs, we'll do what we need to make the navigation stack there work the way we want.
