### ISSUE TITLE
(Question) What is the ETA to leave beta?

### ISSUE THREAD

**Issue by hardBSDk** [zulip/zulip-flutter#788]

**Comment by gnprice** [comment]
There's no fixed timeline — this app will launch, replacing the legacy zulip-mobile app, when it's ready.

I've previously referred to ["late this year"](https://github.com/zulip/zulip-flutter/issues/418#issuecomment-1963072737) as a possible timeframe. Probably the next time that we re-evaluate the overall state and make a new rough timeline will be in September, after the current GSoC program and the August vacation season are complete. For week-by-week updates, one can take a look at the long-running thread [#mobile-team > Flutter beta timeline](https://chat.zulip.org/#narrow/stream/243-mobile-team/topic/Flutter.20beta.20timeline/near/1796878) on chat.zulip.org.
