### ISSUE TITLE
Show unread markers in message list

### ISSUE THREAD

**Issue by gnprice** [zulip/zulip-flutter#79]
This means:
* Track which messages are read vs. unread.
* When a message in the message list is unread, show that with an unread-message marker (https://zulip.com/help/marking-messages-as-read).
* When a message that was unread becomes read, remove the marker with a fading animation, just like Zulip web and zulip-mobile.

To make the UX fully hang together, we'll follow up with:
* #80 
* #81

**Comment by sirpengi** [comment]
@gnprice Ready for review! In general we've kept small prep commits at the beginning of the PR chain but I've put two commits more related to the animation bugfix before the fix itself as I think they're more semantically connected. They are quite easily reordered in any case.
