### ISSUE TITLE
Make use of thumbnails

### ISSUE THREAD

**Issue by alya** [zulip/zulip-flutter#799]
In https://github.com/zulip/zulip/issues/16210, we're implementing thumbnailing for uploaded images.

We should use thumbnails in the mobile app. In particular, the message view should show thumbnails, while the lightbox should download the full-scale images.

Blockers:
- https://github.com/zulip/zulip/issues/16210

**Comment by gnprice** [comment]
For implementing this feature, the pieces we'll need are:
* There's a [new bit of HTML for a placeholder](https://chat.zulip.org/#narrow/stream/378-api-design/topic/thumbnail.20placeholder/near/1833796) where the server is preparing a thumbnail.

  We'll need to parse that in `lib/model/content.dart`, and then build an appropriate widget to show the desired UI: a spinner similar to what Zulip web shows.

* In images in message content, the HTML will look very similar but the two image URLs that appear (one at the `href` of an enclosing `a`, one at the `src` of an `img`) will start being different from each other: one is the thumbnail and one the original image.

  We'll need to start tracking both those URLs in the content parser. Then we'll use one for the image in the message list, and the other for the lightbox.

  The "Copy link" feature in the lightbox should also get the original full-size image. I think this will happen automatically given a natural implementation of the rest of the feature, but it should be included as one of the test cases.
