### ISSUE TITLE
Support @topic wildcard mentions

### ISSUE THREAD

**Issue by PIG208** [zulip/zulip-flutter#817]
This Zulip feature (https://zulip.com/help/mention-a-user-or-group#mention-all-topic-participants).
API docs: https://zulip.com/api/update-message-flags#available-flags
Relevant discussions: https://chat.zulip.org/#narrow/stream/378-api-design/topic/highlight.20topic-wildcard.20mention/near/1621613

**Comment by gnprice** [comment]
This has a couple of different parts, which we might split into several issues when we start working on it.
* Understanding the new pair of flags for stream/channel vs. wildcard mentions.
* Offering these in autocomplete, as part of #234.
* Highlighting these in the message list: #646, #647.

**Comment by gnprice** [comment]
OK, I've split this up into those more-specific issues, and edited the comment above to point to them. Closing this umbrella issue in favor of using those to track the work.
