### ISSUE TITLE
msglist: Find web's dark-theme color for typing-indicator text; add to `MessageListTheme`

### ISSUE THREAD

**Issue by chrisbobbe** [zulip/zulip-flutter#858]
@PIG208, would you be able to do this, as a followup to your PR #790 which was merged? Here's the color that should be updated:

```dart
    return Padding(
      padding: const EdgeInsetsDirectional.only(start: 16, top: 2),
      child: Text(text,
        style: const TextStyle(
          color: HslColor(0, 0, 53), fontStyle: FontStyle.italic)));
```

**Comment by gnprice** [comment]
Cross-linking: this forms part of #95.

**Comment by chrisbobbe** [comment]
I'll go ahead and take this; it should be quick, and I'd like to get it done today if I can. 🙂
