### ISSUE TITLE
Handle codehilite elements with multiple classes

### ISSUE THREAD

**Issue by PIG208** [zulip/zulip-flutter#933]
It is totally possible for Pygments to [generate HTML elements with more than one classes](https://github.com/pygments/pygments/blob/07b69d42ca431249250195e7f7fbd21e1ccdfb2c/pygments/formatters/html.py#L853-L855).

This is considered quite an edge case and only happens to some languages, such as PostgreSQL (see https://github.com/pygments/pygments/issues/2780). It currently renders as an unimplemented feature whenever a code block contains tokens with more than one classes.

See a minimal example [here](https://chat.zulip.org/#narrow/stream/7-test-here/topic/tap/near/1939061).

HTML of the unsupported message:

```html
<pre>
  <span></span>
  <code>
    <span class="s s-Name">"</span>
  </code>
</pre>
```

**Comment by PIG208** [comment]
Listed under #921.

**Comment by gnprice** [comment]
Other than PostgreSQL, this apparently happens with YAML. Here's [a test message](https://chat.zulip.org/#narrow/stream/7-test-here/topic/Greg/near/1949014).

**Comment by PIG208** [comment]
For these kind of messages, we should be able to safely apply the style of the most specific known class from the class list. These non-standard token types usually aren't likely to be handled by styles. We could also maintain a list of unexpected token types, but that does not seem necessary.
