### ISSUE TITLE
Update "bot" icon

### ISSUE THREAD

**Issue by gnprice** [zulip/zulip-flutter#978]
When a message was sent by a bot, we put an icon by the sender's name to indicate it's a bot.

In the web app the icon we use was recently redesigned:
* https://github.com/zulip/zulip/pull/31673
* https://chat.zulip.org/#narrow/stream/101-design/topic/notification.20bot.20icon/near/1918735

to a friendlier-looking "bot" face with one antenna instead of two antennas. We should update to the new one-antenna icon.

Reported by @alexmv in chat: https://chat.zulip.org/#narrow/stream/48-mobile/topic/Bot.20icon.20asset.20needs.20update/near/1953361

**Comment by fombalang** [comment]
Hi @gnprice 
I would like to work on this issue, please.

**Comment by gnprice** [comment]
Sure, please go ahead.

**Comment by fombalang** [comment]
Alright!

**Comment by fombalang** [comment]
Hello
I have updated the bot icon.

![Screenshot_20241004-085226](https://github.com/user-attachments/assets/782db678-9e6e-412e-bebf-8ca7a2c52c68)

![Screenshot_20241004-085217](https://github.com/user-attachments/assets/6ce5a689-6a13-4eac-8157-1dd90f69fa97)

Before I send a PR for this, I would like to verify if a change like this would require that tests be made or updated? Seeing as I only updated the icon SVG file and ran the `tools/icons/build-icon-font` command without changing any Dart code?

Thank you

**Comment by gnprice** [comment]
Cool ­— please go ahead and send the PR. This change will be fine without tests.

In general if you have a change that you think may not need tests, I recommend sending the PR without tests but then calling that question out clearly in the PR description. That helps speed things along if reviewers agree that tests aren't needed. It also means reviewers can see the rest of your changes, which can help answer the question of whether tests are needed.

**Comment by fombalang** [comment]
Okay, Understood
